### ISSUE TITLE
Custom visualization plugin not working for charts. 

### ISSUE THREAD

**Issue by snehlata08** [apache-superset/superset-ui#1026]
I followed this tutorial https://superset.apache.org/docs/installation/building-custom-viz-plugins to create a custom viz plugin for superset. But somehow the generated plugin is never shown in the chart selection wizard. 

Then i researched and found this bug https://github.com/apache-superset/superset-ui/issues/794 on github but the answers given over there are also not working. 

When i run 
`yarn jest`  
I get the following error 
![image](https://user-images.githubusercontent.com/79985986/112310211-5149b700-8cca-11eb-8d22-5bdfc3b528e8.png)

While running npm run dev-server i get this error 
![image (2)](https://user-images.githubusercontent.com/79985986/112311055-45aac000-8ccb-11eb-9cc1-05a19b57362a.png)

- superset-ui version: `v0.15.2`
- Node version: `v14.15.0`
- npm version: `6.14.8`

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
