### ISSUE TITLE
superset-ui-connection: Allow callAPI to handle PUT and PATCH requests to support superset SQLlab

### ISSUE THREAD

**Issue by fabiomendescom** [apache-superset/superset-ui#104]
**Is your feature request related to a problem? Please describe.**
The call API in super ui connection component currently only supports the POST command. SQLlab in superset, when saving queries, executes a PUT request to save queries. Because that function uses this component, this component needs to be changed to allow for PUT and PATCH to be executed as well. By support I mean parsing the payload in json into form variables for the request. The call API only does this for POST only. See this for the problem in superset -> https://github.com/apache/incubator-superset/issues/5804 

**Describe the solution you'd like**
The call API should work exactly the same (parsing JSON payload into form parameters) for PUT and PATCH the same way

**Describe alternatives you've considered**
SQLlab is already developed with SQLAlchemy to use these other verbs automatically in the framework. Changing this outside of the callAPI would be too cumbersome and unnecessary, considering that this support should exist in this component.

**Additional context**
The change is fairly simple. The call API should simply allow these additional verses to be used. See the

**Comment by fabiomendescom** [comment]
https://github.com/apache-superset/superset-ui/pull/105 pull request created

**Comment by kristw** [comment]
related to #85

**Comment by kristw** [comment]
Released with `@superset-ui/connection` `0.10.2`
