### ISSUE TITLE
What is superset-ui? How to use it?

### ISSUE THREAD

**Issue by aksth** [apache-superset/superset-ui#1117]
It's mentioned that superset-ui is a "Collection of packages that power the Apache Superset UI, and can be used to craft custom data applications that leverage a Superset backend".

Mostly, these packages are the individual components that we can find in the superset, i.e. core (connection, number-format, etc.) and charts (table, bar, area, pie, choropleth, etc.).

What is the main purpose of superset-ui? What is the difference between core packages and chart packages? How to actually use these different packages?

For example,

Let's say I have made a simple dashboard in my superset application.
Will I be able to show that dashboard in my other application (having Angular, React, etc.) using superset-ui?
Although there is no separate dashboard package in superset-ui, I'm guessing we have to use the individual components that make up a dashboard, right?

Even for the chart components, how do we feed the data to it?

For example, in legacy-preset-chart-nvd3/Bar, we have JSX as following:

```
<SuperChart_SuperChart
  FallbackComponent={}
  chartType="bar"
  datasource={{
    verboseMap: {}
  }}
  formData={}
  height={400}
  queriesData={}
  width={400}
/>
```

There are fields such as FallbackComponent, datasource, formData, and queriesData. From where do we fill these fields? 

There is a connection component (SupersetClient) available in the core package as well? What is this for? Is it for connecting to the superset backend (where are queries are stored)?

I'm finding it difficult to understand how to connect and use these individual components and use them in my other application (which uses Angular). There seems to be less documentation explaining in detail. So if anybody could clarify it, that'd be great.

**Comment by BFergerson** [comment]
I would also be interested in any answers to the above questions and it seems this line of questioning is rather common:
- https://github.com/apache-superset/superset-ui/issues/1117
- https://github.com/apache-superset/superset-ui/issues/154
- https://github.com/apache-superset/superset-ui/issues/830

I'd appreciate any clarifications on how to integrate Superset components into existing applications.

**Comment by srinify** [comment]
hey @aksth All good questions! I will say that the goal of this repo isn't to directly make these visualizations available for other applications to use just yet. If you just want the charts, your best bet tbh is to use ECharts examples directly! https://echarts.apache.org/en/index.html

This repo exists to support some of the nice-ities of having a multi-repo // not in the main apache repo. There's a lot of context that I won't bore you with, but if you want to learn more about how to use this repo with the Superset project. .. check out:

- https://preset.io/blog/2020-07-02-hello-world/
- Event recording by Amit / Nielsen team on how they manage custom viz plugins in production: https://www.youtube.com/watch?v=HNkPQtfzXK0

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
