### ISSUE TITLE
[Feature request] Add a Pakistan map to Apache superset

### ISSUE THREAD

**Issue by Ibrahim7644** [apache-superset/superset-ui#1131]
### Description
Currently Superset does not have a Country Map of Pakistan.

**Comment by junlincc** [comment]
feel free to open a PR. 🙏

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
