### ISSUE TITLE
Fix Indian Map in Superset

### ISSUE THREAD

**Issue by j-manu** [apache-superset/superset-ui#1135]
The current Indian map in Superset is very inaccurate as it has several states missing. (Ex: Telengana) This happened on https://github.com/apache-superset/superset-ui/pull/1045 

I have reported this on that PR - https://github.com/apache-superset/superset-ui/pull/1045#issuecomment-824715145

There are free and open source shape files of India which is accurate and details are given here - https://github.com/apache-superset/superset-ui/pull/1045#issuecomment-825379978

I unfortunately don't have the skills to convert the shape files to the format expected by superset. It would be great if this can be fixed.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
