### ISSUE TITLE
Add Saudi Arabia to country map

### ISSUE THREAD

**Issue by swarnkiran88** [apache-superset/superset-ui#1138]
I am looking for any commitor who can commit it country map
[saudi arabia.zip](https://github.com/apache-superset/superset-ui/files/6566385/saudi.arabia.zip)

**Comment by mhewedy** [comment]
I can send a PR, but first what is your source for the geojson? so I can mention the source in the PR as well.

**Comment by mhewedy** [comment]
BTW, the data is not so accurate, as shown below.

![image](https://user-images.githubusercontent.com/1086049/138222787-05d61c3e-a7b0-4c1c-8086-2fb9074aa724.png)

**Comment by mhewedy** [comment]
I found the version on Elastic.co here https://maps.elastic.co/#file/saudi_arabia_provinces is not accurate as well. still I can depend on thier list as the source for PR

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
