### ISSUE TITLE
error @superset-ui/monorepo@0.0.0: The engine "node" is incompatible with this module. Expected version "14.x". Got "12.22.1"

### ISSUE THREAD

**Issue by shashi5678** [apache-superset/superset-ui#1190]
### Describe the bug

tried to follow 
https://superset.apache.org/docs/installation/building-custom-viz-plugins

### To Reproduce

1.  sudo yarn install

yarn install v1.22.10
[1/5] Validating package.json...
error @superset-ui/monorepo@0.0.0: The engine "node" is incompatible with this module. Expected version "14.x". Got "12.22.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.rsion: [e.g. v0.5.0]
- Node version: `node -v`
- npm version: `npm -v`

**Comment by atirekkumar** [comment]
I got the same error while trying to follow the same tutorial. It got fixed by changing the default version of node installed to 14.x and restarting the terminal. 
https://stackoverflow.com/questions/7718313/how-to-change-to-an-older-version-of-node-js

**Comment by 1758973467** [comment]
you can see package.json see engines field 
```
"engines": {
    "node": "14.x",
    "npm": "^7.5.4",
    "yarn": ">=1.13.0"
  },
```

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
