### ISSUE TITLE
export Metric was not found in @superset-ui/core

### ISSUE THREAD

**Issue by NicolasNeubauer** [apache-superset/superset-ui#1195]
### Discussed in https://github.com/apache-superset/superset-ui/discussions/1167

<div type='discussions-op-text'>

<sup>Originally posted by **NicolasNeubauer** June 11, 2021</sup>
after running
```
npm i @superset-ui/core
npm i @superset-ui/plugin-chart-echarts
```

and including the library through
```
import {
  EchartsTimeseriesChartPlugin,
  EchartsPieChartPlugin
} from '@superset-ui/plugin-chart-echarts'

new EchartsTimeseriesChartPlugin().configure({ key: 'echarts-ts' }).register()
new EchartsPieChartPlugin().configure({ key: 'echarts-pie' }).register()
```

I get the following error:

```
Failed to compile.

./node_modules/@superset-ui/chart-controls/esm/types.js
Attempted import error: 'Metric' is not exported from '@superset-ui/core'.
```

This is also reported in an SO question (by someone else):
https://stackoverflow.com/questions/67585461/export-metric-was-not-found-in-superset-ui-core-error-in-node-modules

How do I get this to work?
</div>

**Comment by stanislavHamara** [comment]
+1 on this

I started a blank new React app with `yarn create react-app superset-test --template typescript`

These are the dependencies :
```json
"dependencies": {
    "@emotion/cache": "^11.4.0",
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "@superset-ui/core": "^0.18.2",
    "@superset-ui/legacy-preset-chart-nvd3": "^0.18.2",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "antd": "^4.16.13",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-loadable": "^5.5.0",
    "react-scripts": "4.0.3",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1"
  },
```

and the App.tsx, where the SuperChart is copied from [here](https://apache-superset.github.io/superset-ui/?path=/story/legacy-chart-plugins-legacy-preset-chart-nvd3-bar--basic):

```tsx
import { BarChartPlugin } from "@superset-ui/legacy-preset-chart-nvd3";
import { SuperChart } from "@superset-ui/core";

function App() {
  
  new BarChartPlugin().configure({ key: "bar" }).register();
  return (
      <div className="App">
        <SuperChart
           chartType="bar"
             .....
        />
      </div>
  )
}

```

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
