### ISSUE TITLE
package.json dependencies and devDependencies

### ISSUE THREAD

**Issue by 1758973467** [apache-superset/superset-ui#1234]
Your question.

- Can we split dependencies into dependencies and devDependencies?

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
