### ISSUE TITLE
In ingonito getting Security error when embedding dashboard in iframe

### ISSUE THREAD

**Issue by saurabnigam** [apache-superset/superset-ui#1252]
[https://github.com/apache/superset/issues/15819](url)

**Comment by saurabnigam** [comment]
https://github.com/apache-superset/superset-ui/blob/4be2c55f8fcf035aee3f39f31dbd264ecda8f2c7/packages/superset-ui-core/src/connection/callApi/callApi.ts#L72

**Comment by saurabnigam** [comment]
This line is throwing Security Error when the dashboard is embedded and is open in ingonito

**Comment by saurabnigam** [comment]
Any insights or guidance will be appreciated! I can open a pr if I know how to fix!

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
