### ISSUE TITLE
Add support for 2 decimal point formatting for D3 formatting in charts

### ISSUE THREAD

**Issue by jayakrishnankk** [apache-superset/superset-ui#1274]
### Is your feature request related to a problem? Please describe.

While formatting numbers, it is possible to select 1 point precision or 3 point precision. But there is no 2 point precision. Our users are very particular about this, and they need a 2 point precision formatting on their % formatted numbers.

### Describe the solution you'd like

Allow 2 point precision to be selected from the D3 formatting dropdown.

### Describe alternatives you've considered

We tried one point and 3 point formats and our users were not very happy with it.

### Additional context\*\* Add any other context or screenshots about the feature request here.
![Untitled](https://user-images.githubusercontent.com/1909466/128245703-18a7d2ef-ac32-443d-9295-e8aab75f090a.jpg)

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
