### ISSUE TITLE
add a new option to callApi, to turn conditional request on/off.

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#128]
**Is your feature request related to a problem? Please describe.**
`callApi` `GET` use the etag and cached results by default. There is no choice to opt-out. 

**Describe the solution you'd like**
Add a new option to callApi, to turn conditional request on/off.

This is a follow-up from #119

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
