### ISSUE TITLE
how to link superset-ui and superset-frontend

### ISSUE THREAD

**Issue by AUSERGEE** [apache-superset/superset-ui#1280]
I followed the steps below, but failed:

**/superset-bi/superset-ui/plugins/plugin-chart-echarts：**
npm install
npm install --legacy-peer-deps

**/superset-ui：**
yarn
yarn build

**/superset-bi/superset-frontend：**
npm link ../superset-ui/plugins/plugin-chart-echarts
npm run dev-server

**Comment by stephenLYZ** [comment]
/superset-bi/superset-ui/plugins/plugin-chart-echarts：
npm install
npm link

/superset-ui：
yarn
yarn build

/superset-bi/superset-frontend：
npm link @superset-ui/plugin-chart-echarts
npm run dev-server

**Comment by AUSERGEE** [comment]
好的，已链接成功，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache-superset/superset-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 晚上9:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache-superset/superset-ui] how to link superset-ui and superset-frontend (#1280)





 
/superset-bi/superset-ui/plugins/plugin-chart-echarts：
 npm install
 npm link
 
/superset-ui：
 yarn
 yarn build
 
/superset-bi/superset-frontend：
 npm link @superset-ui/plugin-chart-echarts
 npm run dev-server
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
