### ISSUE TITLE
Loader errors when trying to build superset with new version of legacy-plugin-chart-country-map plugin

### ISSUE THREAD

**Issue by Anushka-Hapukotuwa** [apache-superset/superset-ui#1301]
I am using apache superset 1.2
I added a country map to the @superset-ui/legacy-plugin-chart-country-map and the PR was successfully merged to the superset-ui repo. Next I tried to update the superset/superset-frontend/package.json (in apache superset 1.2) file with the latest version of @superset-ui/legacy-plugin-chart-country-map -> 0.17.81, but it is giving some loader errors.
Screenshots - 
Version update of @superset-ui/legacy-plugin-chart-country-map:
![image](https://user-images.githubusercontent.com/87460606/129023476-db9b9f18-069c-453a-b943-d75111fb820e.png)

Gave npm install first and then gave npm run build.
Errors generated when running npm run build:
![MicrosoftTeams-image (49)](https://user-images.githubusercontent.com/87460606/129023725-f6d973b9-d267-4d52-9073-45a748e47aef.png)

Superset version - 1.2
@superset-ui/legacy-plugin-chart-country-map - 0.17.81
npm version - 6.14
node version - 14.17.2

**Comment by villebro** [comment]
Unfortunately `0.17.81` plugins are not compatible with Superset v1.2. But all hope is not lost! The forthcoming v1.3 will feature the new maps (release candidate 2 most likely coming out before the weekend with the final version expected to ship sometime next week).

**Comment by Anushka-Hapukotuwa** [comment]
thanks for the clarification @villebro

**Comment by Anushka-Hapukotuwa** [comment]
Got the loader errors resolved but now the finland map is not loading as expected.
The steps followed to resolve the loader errors were:
1. Add the new version of the plugin to the package.json but without deleting the package-lock.json, kept it as it is and gave npm install command. Afterwards, the updated version of the plugin was reflected in the package-lock.json file.
2. The newly added countries were present under the country map charts.

But now the Finland map is not loading as expected.
The map is there but it seems to be stuck in a corner. Is this a problem with the geojson file or something else?
![finland-country-map-not-loading](https://user-images.githubusercontent.com/87460606/129517883-dbd9fb30-b051-415d-b484-14f3811a1ab6.PNG)

The Austria map which was also newly added is loading as expected.
![austria-map-loading](https://user-images.githubusercontent.com/87460606/129518452-d81bd649-6593-4b05-abc6-2371b58432a3.PNG)

Superset - v1.2
@superset-ui/legacy-plugin-chart-country-map - v0.17.81
PR for adding Finland map - https://github.com/apache-superset/superset-ui/pull/1258
PR for adding Austria map - https://github.com/apache-superset/superset-ui/pull/1267

**Comment by Anushka-Hapukotuwa** [comment]
Fixed in #1321
Finland map loading accurately in @superset-ui/legacy-plugin-chart-country-map version -> 0.18.0
