### ISSUE TITLE
Add Scatter Chart to plugin-chart-echarts

### ISSUE THREAD

**Issue by kaihenzler** [apache-superset/superset-ui#1318]
### Is your feature request related to a problem? Please describe.

This is a feature request or rather a request for comments to add Scatter Charts to `@superset-ui/plugin-chart-echarts` 

### Describe the solution you'd like

We developed a Scatter Chart plugin based on echarts in a separate repository for the ease of moving fast and to get a working version up and running: https://github.com/w11k/superset-chart-plugins/blob/master/plugins/plugin-chart-scatter/README.md

The package is published on npm and can be tested via 

`npm install @w11k/plugin-chart-scatter`

and is set up as usual by importing it

```js
import EchartsScatterChartPlugin from '@w11k/plugin-chart-scatter';

new EchartsScatterChartPlugin().configure({ key: 'scatter' }).register();
```

I'm opening this issue to gather feedback if some folks are interested to have the Scatter Chart integrated into this repository. I would go ahead a create a PR that integrates it.

### Describe alternatives you've considered

If there is no interest in integrating the new chart type into this repo the issue can be closed.

### Additional context

There are 2 main versions the chart can be used for.

#### 1. Aggregated Data

X, Y and Bubble Size (optional) can be aggregated and grouped and colored accordingly

![aggregated](https://user-images.githubusercontent.com/4253453/130068969-8d795a1d-dd07-4c8a-a1ce-67e78b69a457.png)

#### 2. Raw Data
![raw](https://user-images.githubusercontent.com/4253453/130068976-02b47ed4-2fe1-41f2-b294-733d13be229e.png)

X, Y and Bubble Size (optional) metric can be selected to plot plain datapoints

#### General Settings

- A Regression line (linear, polynominal, logarithmic, exponential) can be drawn 
- Min/Max Size of the bubble is adjustable
- X,Y Axis Labels are Adjustable
- Legend is adjustable

#### Control Panel

Aggregated Options
![aggregated-options](https://user-images.githubusercontent.com/4253453/130069932-3f59a621-e1b2-44ea-bb63-3ce8cbf90ea4.png)

Raw Options
![raw-options](https://user-images.githubusercontent.com/4253453/130069936-8e119a7c-28c3-45e7-a47c-5cafc86403ae.png)

Common Options
![common-options](https://user-images.githubusercontent.com/4253453/130069934-bbdadd18-9670-4dd7-831a-5166f408ff56.png)

**Comment by junlincc** [comment]
hi @kaihenzler thanks for offering the contribution! this is absolutely aligned with our product goal. we current have a time series scatter plot but not a generic one(x-aixs for non temporal columns) like you built. we would love to find way to integrate it! do you mind filing your issues and question in the main superset repo for faster response, going forward?

@villebro @stephenLYZ @zhaoyongjie

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
