### ISSUE TITLE
plugin update question

### ISSUE THREAD

**Issue by ab291478089** [apache-superset/superset-ui#1343]
Will it work if I upgrade only one dependency to v0.18.0

**Comment by ab291478089** [comment]
hello everyone，Can i add a react-resizable effect to the pivot table v2 to change the column width

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
