### ISSUE TITLE
error TS2339: Property 'advancedAnalytics' does not exist on type 'typeof import("/packages/superset-ui-chart-controls/lib/sections")'.: numeric argument required lerna ERR! ../../scripts/tsc.sh       --build exited 2 in '@superset-ui/plugin-chart-echarts'

### ISSUE THREAD

**Issue by kachely** [apache-superset/superset-ui#1357]
When I tried to build the version 0.17.81, an error occurred.
error TS2339: Property 'advancedAnalytics' does not exist on type 'typeof import("/packages/superset-ui-chart-controls/lib/sections")'.: numeric argument required lerna ERR! ../../scripts/tsc.sh       --build exited 2 in '@superset-ui/plugin-chart-echarts'

How can I do to solve this?

**Comment by zhaoyongjie** [comment]
Hi @kachely , How do you build `superset-ui`? Could you share your step for building?

**Comment by kachely** [comment]
> Hi @kachely, How do you build `superset-ui`? Could you share your steps for building, please?

Thank you!
The issue has been resolved by clean the build from npm.

**Comment by kachely** [comment]
Resolved by clean build from npm.
