### ISSUE TITLE
modify ISO 3166-2, name and geometry of the provinces of Iran in legacy plugin chart country map

### ISSUE THREAD

**Issue by Mohsen-eng74** [apache-superset/superset-ui#1358]
Hello,

both ISO 3166-2 and geometry of the provinces of Iran are outdated. i've checked the [Natural Earth Data](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/) source, but still not valid.

- The valid geometry of the provinces is taken from the [OpenStreetMap](https://overpass-turbo.eu/s/1aZM) with some modification (symmetric difference applied to get the land border). also, OpenStreetMap geometry is more compatible with [approved provincial map](https://www.ncc.gov.ir/images/docs/files/000004/nf00004390-1.jpg) by the Ministry of Interior of the Islamic Republic of Iran.
- the valid  ISO 3166-2 is taken from [iso.org](https://www.iso.org/obp/ui/#iso:code:3166:IR).

With Best Regards.

**Comment by Mohsen-eng74** [comment]
https://github.com/apache-superset/superset-ui/pull/1359

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
