### ISSUE TITLE
Emit multiple filters from Pivot Table V2

### ISSUE THREAD

**Issue by cccs-jc** [apache-superset/superset-ui#1369]
The Pivot Table v2 is able to emit filters to other charts in a dashboard. However I'm unable to emit more than one filter at a time.

It would be very useful to be able to click on multiple cells to emit filters. Perhaps re-clicking on the selected cells to turn them off.

I tried to use SHIFT, CTRL keys while clicking but it did not do what I would have expected.

![image](https://user-images.githubusercontent.com/56140112/134064728-c4adcd83-bd8f-4aad-9d69-ca223b8a6bfe.png)

**Comment by cccs-jc** [comment]
It looks like the code to support multiple filters in the Pivot Table v2 is commented out

```javascript
      // multi select
      if (selectedFilters && isActiveFilterValue(key, val)) {
        updatedFilters[key] = selectedFilters[key].filter((x: DataRecordValue) => x !== val);
      } else {
        updatedFilters[key] = [...(selectedFilters?.[key] || []), val];
      }
```
 Is that because there is a button missing to toggle between either a single filter or the list of filters up to the one clicked.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
