### ISSUE TITLE
what exactly is superset-ui !?

### ISSUE THREAD

**Issue by nileio** [apache-superset/superset-ui#1382]
- can we use those storybook components in a React/JS/Vue app?
- is this only used to create custom vis types that can be used in superset application for building new charts? https://preset.io/blog/2020-07-02-hello-world/
but it cant be just for that purpose because how then the storybook have the core components too , including echarts.
- if we build a chart in superset and like to use it as a component in our js app ? is this something actually in the roadmap?
- can we possibly have a simple ReadMe.md with some information for developers ?
I mean 
>Collection of packages that power the Apache Superset UI, and can be used to craft custom data applications that leverage a Superset backend

`craft custom data applications that leverage a Superset backend` what does that really mean!?
@villebro @kristw 
thank you!

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
