### ISSUE TITLE
Pivot table display 0 like "0.000000"

### ISSUE THREAD

**Issue by NinjaDev06** [apache-superset/superset-ui#1412]
### Describe the bug

The Pivot table display some 0 value like "0.0" and sometime like "0.000000". In the View Results, they are all display like "0".

I tried to set a D3 format ".1f" but it do not affect the 0 values.

### Expected behavior

All zero values should be shown like "0" because I didn't ask to add decimal.

### Screenshots

Without D3 format
![image](https://user-images.githubusercontent.com/1877413/137972906-5c8ea089-87e4-4ed3-973d-6dd65a7063df.png)

With D3 format
![image](https://user-images.githubusercontent.com/1877413/137972396-809ce61d-c40d-4813-98b6-0355480a8f74.png)

### Environment:

- superset-ui version: 1.2.0

### Additional context

May be a duplicate of https://github.com/apache-superset/superset-ui/issues/745

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
