### ISSUE TITLE
Google Map Integration as visualisation

### ISSUE THREAD

**Issue by patilvikram** [apache-superset/superset-ui#142]
We are working with Superset for last 6 months and primarily using it as a visualization tool with Druid. Recently we tried out Mapbox but could not find any google map integration free or licensed version. 

We would be happy to contribute but you guys can review PR whenever you organize and make things stables but It would be great if you can share some pointers about integration new visualizations.

I see that I need to update viz.py and few js files. But still not very clear about new structures with plugin development. Some pointers will be very helpful.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
