### ISSUE TITLE
Drag and Drop user-reorganizable columns in the Table Viz

### ISSUE THREAD

**Issue by stevetracvc** [apache-superset/superset-ui#1420]
### Is your feature request related to a problem? Please describe.

Sometimes the dashboard designer doesn't know how the end user will want their columns organized in a table. Why not let the user rearrange the columns themselves if they want?

### Describe the solution you'd like

react-table has a built-in useColumnOrder hook, and there was a discussion online about how to implement drag-and-drop in a react-table.
https://github.com/tannerlinsley/react-table/issues/256

### Describe alternatives you've considered

None, this is the easiest approach.

### Additional context\*\* Add any other context or screenshots about the feature request here.

I've implemented it in a custom viz I built that is based on the table viz, and so I can redo it in the original plugin and issue a PR soon.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
