### ISSUE TITLE
The DeckGL Multi chart plugin does not work for a local superset instance

### ISSUE THREAD

**Issue by abdullah-mukadam** [apache-superset/superset-ui#1473]
### Bug Description

I am running superset locally, using a docker image given in the documentation. The DeckGL Multi chart plugin gives a blank screen when I try to add a couple of my existing deckgl charts to it. I was making a custom deckgl chart plugin and found this issue in the DeckGL multi chart plugin for my local setup. I thought it was because of my plugin but when I tried it on the official docker image it doesn't seem to work there too. The console gives an error saying "TypeError: colnames not iterable"

### To Reproduce

1. Go to 'deck.gl Multi Chart plugin'
2. Select a few deck.gl charts to add to the visualization.
3. Click on 'Run Query'
4. A blank screen will be visible, check the console for the error "TypeError: colnames not iterable"

### Expected behavior

The deckgl charts should be composed in a single chart and should be visible.

**Comment by junlincc** [comment]
@abdullah-mukadam Thanks for the issue. Please file future issue in our main repo going forward so we can attend to it faster. We have this issue added to backlog, but please let us know if you would like to contribute.

**Comment by abdullah-mukadam** [comment]
Okay I'll file issues in the main repo going forward. I'll see if I can contribute to this, thanks a lot !

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
