### ISSUE TITLE
No filter emitted when no group by column specified

### ISSUE THREAD

**Issue by cccs-jc** [apache-superset/superset-ui#1475]
When using Time-Series Bar Chart v2, the visualization will create aggregates by time grain. In this case by `order_date` by month.

If you do not specify an columns to group by you get a total count for the month.

![Screen Shot 2021-11-24 at 7 31 53 AM](https://user-images.githubusercontent.com/56140112/143239743-16f0194b-88e9-416d-afc7-88d09a726a49.png)

![Screen Shot 2021-11-24 at 7 33 12 AM](https://user-images.githubusercontent.com/56140112/143239731-be95adaa-92aa-402b-a0b6-7a05350abcb4.png)

When you place that visualization inside a dashboard and click on a given month the viz does not emit any filters for that `order_date` month.

The code https://github.com/apache-superset/superset-ui/blob/3e1699542808f0720a6c05d95fc95f557d5c90fc/plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx#L102 will only emit filters for columns that are involved in a group by.

When there are no group by it should emit based on the implicit time grain group by. In this case since it's a time grain the emitted filter should be a time range. For example `order_date >= selected_date AND order_date < (order_date + 1 month)`

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
