### ISSUE TITLE
Enhancements to Table Plugin

### ISSUE THREAD

**Issue by stevetracvc** [apache-superset/superset-ui#1480]
I have several other enhancements I've made to the table plugin that my coworkers have liked. I'm opening this up to a discussion on whether any of the features would be good additions for everyone. A few are still WIP but most seem to be working as expected. Unfortunately, while many of them don't depend on each other, they do _affect_ each other, so it would take a little effort for me to make them all separate PRs. I don't mind doing it, but I'd need to see which things you'd want before trying to untangle them.

Here's the list:
1. A row numbers column, where the numbers stay fixed even after sorting the other columns
2. Sticky columns, like Excel Freeze Columns  (WIP)
3. Two-level Column Headers, allowing you to group columns together with a higher-level header (WIP)
4. Truncate long text and expand when hovering

Here are some vids:

Row Number column:
![table_row_numbers_1](https://user-images.githubusercontent.com/70416691/144452791-38b403e3-6820-47a7-b7e1-c922247bbbd4.gif)

![table_row_numbers_2](https://user-images.githubusercontent.com/70416691/144452813-08577343-2dd3-43fb-9f60-85e77af088b0.gif)

Freeze Columns:
![table_freeze_columns](https://user-images.githubusercontent.com/70416691/144452893-8be67cbb-cef0-4fa6-8c03-2151f7c87c59.gif)

Column Grouping/Headers:
adding:
https://user-images.githubusercontent.com/70416691/144466015-9ee07130-493f-4fe7-b0a9-c22e000cce1c.mp4

deleting:
https://user-images.githubusercontent.com/70416691/144466126-822335f9-4273-48b9-a620-388edecd14b8.mp4

Truncating long cells (it's more useful when the text is really really long though):
https://user-images.githubusercontent.com/70416691/144466874-5eded8a0-dd0b-46fc-ae55-a3ae16f24117.mp4

Known issues:
1. row numbers + two-level column header can result in weird row number location
2. sticky columns currently requires sticky column widths to be manually set
3. sticky columns doesn't work with cell bars (background is set to white, which is overridden by cell bars)
4. truncate might be better as a per-column setting, rather than table-wise (I didn't know how to add to that section when I first added the feature :) )

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
