### ISSUE TITLE
Documentation for how to use React components

### ISSUE THREAD

**Issue by yuguang** [apache-superset/superset-ui#154]
Are there documentation pages for the React components? One of the objects I am getting from our front-end dev is that the documentation on how to create charts is lacking.

**Comment by Smilebags** [comment]
Definitely agree. I've found myself here after having troubles updating superset and my custom visualisation breaking. I can't find any documentation on how to add a new visualisation to superset now, but it seems they're coming from a completely separate repo now?

**Comment by Dhara159** [comment]
Hey @Smilebags , I'm facing the same issues because of a lack of information provided in the documentation. Could you please share any reference to the blog or article which can lead to a straightforward and simple implementation?

**Comment by zheya08** [comment]
+1

**Comment by pkhodaveissi** [comment]
+1

**Comment by gauravencoded** [comment]
I am also facing similar issues.

**Comment by orenteriab** [comment]
Hey folks! Do any of you have had any news on this?

I'm facing some pretty weird issues using this components. I'm starting to think these superset-ui components are not meant to be used out of superset. I have made the chart api return some data, and to render tables, but for some reason I'm not able to render pie charts.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
