### ISSUE TITLE
How often Superset UI is released?

### ISSUE THREAD

**Issue by fstaoe** [apache-superset/superset-ui#189]
Hi all, 

This PR (https://github.com/apache-superset/superset-ui/pull/182) is solving an issue that it's important for me, no pressure on that :) but I would like to know how often you release Superset UI or when are going to release the next version?

Thank you in advance.

**Comment by williaster** [comment]
Hi @fstaoe, thanks for checking out `@superset-ui`. We release as needed for the time being (auto-releases hopefully coming soon!). I just attempted to release but tests are failing locally. I'll take another shot at this early next week (after the holiday tomorrow in the US 🇺🇸 🎆)

**Comment by fstaoe** [comment]
Hi @williaster,

Thank you very much for your reply. I will keep checking next week.

Enjoy the holiday!
