### ISSUE TITLE
is CORS working for anybody ?

### ISSUE THREAD

**Issue by deresegetachew** [apache-superset/superset-ui#204]
I have been trying to run superset-storybook for 2 days now and I keep on getting CORS error. 
Yes I have followed the guides ; installed superset[cors] and set enable_cors to true;

other than that I have also followed this guide 
https://github.com/apache-superset/superset-ui/pull/118#issue-260924446

looking at the response from the server i noticed we are not getting the response header
Access-Control-Allow-Origin

this is what my **superset_config.py** looks like

```
ENABLE_CORS = True
CORS_OPTIONS = {
    'supports_credentials': True,
    'allow_headers': [
        'X-CSRFToken', 'Content-Type', 'Origin', 'X-Requested-With', 'Accept',
    ],
    'resources': [
         '/superset/csrf_token/'  # auth
         '/api/v1/formData/',  # sliceId => formData
         '/superset/explore_json/*',  # legacy query API, formData => queryData
         '/api/v1/query/',  # new query API, queryContext => queryData
         '/superset/fetch_datasource_metadata/'  # datasource metadata

    ],
    'origins': ['http://localhost:9001','http://localhost:3000'],
}
```

And the following are the error in chrome and HTTP request and response headers.

![Screenshot from 2019-08-14 15-31-31](https://user-images.githubusercontent.com/2713659/63021563-86184a00-bea9-11e9-86c4-6ac9071dacc0.png)
![Screenshot from 2019-08-14 17-02-42 (1)](https://user-images.githubusercontent.com/2713659/63027423-9e8e6180-beb5-11e9-955e-5c22296afa05.png)

**FYI the superset-storybook live demo does n't work as well.**
https://apache-superset.github.io/superset-ui/

has any one faced the same issue ?
thank you

**Comment by williaster** [comment]
@deresegetachew which browser are you using? chrome `v76` broke this for us and were were able to fix it by setting `chrome://flags/#out-of-blink-cors` to `disabled` (`v75` was `disabled` by default, `v76` is `enabled` by default)

**Comment by williaster** [comment]
> FYI the superset-storybook live demo does n't work as well.

This is because there is no public superset instance for it to talk to.

**Comment by deresegetachew** [comment]
hi @williaster thank you for the response. I have tried both FireFox and Chrome ; I did set `out-of-link-cors` to `disabled` as you mentioned but I am still getting the CORS errors in chrome as well as firefox. 

In chrome it fails to load the response data, while in fire-fox I get the token but still get a CORS Warning. I have attached a screen shot of the errors in chrome and firefox below.

--Error in Chrome--
![Screenshot from 2019-08-15 10-10-17](https://user-images.githubusercontent.com/2713659/63078878-9bdb4d00-bf45-11e9-9780-25236013ee74.png)

--Error in FireFox--
![Screenshot from 2019-08-15 10-12-35](https://user-images.githubusercontent.com/2713659/63078879-9bdb4d00-bf45-11e9-9ea7-c3607176084e.png)

---CORS Warning in FireFox and Error in Chrome--

![Screenshot from 2019-08-15 10-13-05](https://user-images.githubusercontent.com/2713659/63078981-dd6bf800-bf45-11e9-9986-6556c78e6e05.png)
![Screenshot from 2019-08-15 10-11-57](https://user-images.githubusercontent.com/2713659/63078991-e230ac00-bf45-11e9-8c5e-5f748a5ad794.png)


Thank you in advance.

**Comment by deresegetachew** [comment]
hi @williaster any ideas how to solve this issues now i am working on moving to production ?

**Comment by deresegetachew** [comment]
Hello; The original code **superset_config.py** was missing a comma :( now it works.
I have added a comma after    '/superset/csrf_token/'.
I actually copied the code from **@superset-connection**




```
ENABLE_CORS = True
CORS_OPTIONS = {
    'supports_credentials': True,
    'allow_headers': [
        'X-CSRFToken', 'Content-Type', 'Origin', 'X-Requested-With', 'Accept',
    ],
    'resources': [
         '/superset/csrf_token/' , # auth
         '/api/v1/formData/',  # sliceId => formData
         '/superset/explore_json/*',  # legacy query API, formData => queryData
         '/api/v1/query/',  # new query API, queryContext => queryData
         '/superset/fetch_datasource_metadata/'  # datasource metadata

    ],
    'origins': ['http://localhost:9001','http://localhost:3000'],
}
```

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
