### ISSUE TITLE
Not able to get the Chart Loaded, Successfully retrieved the payload but not able to render.

### ISSUE THREAD

**Issue by yobnytech** [apache-superset/superset-ui#211]
Hi,

Since NDV3 plugin dont provide typescript interface, created simple definition to expose Bar Chart like below. 
....
```
declare module "@superset-ui/legacy-preset-chart-nvd3" {
  export { default as AreaChartPlugin } from "./lib/Area";
  export { default as BarChartPlugin } from "./lib/Bar";

} 
```

In my component configured the client and BarChartClient as per expectation

```
 SupersetClient.configure({
            host: 'myhost',
            mode: 'cors',
            protocol: "https:",
            headers: { ...Auth },
            csrfToken: 'csrf_token'
        }).init();

       const a = new BarChartPlugin()
            .configure({ key: 'bar' })
            .register();
```

.. received the below payload but the payload is not rendering as NDV3 bar chart 

`{"cache_key":null,"cached_dttm":null,"cache_timeout":10,"error":null,"form_data":{"datasource":"1__druid","viz_type":"bar","url_params":{},"granularity":"P1D","druid_time_origin":null,"time_range":"1970-01-01T00:00:00 : 2019-08-27T00:00:00","metrics":[{"expressionType":"SIMPLE","column":{"id":11,"column_name":"value_sum","verbose_name":null,"description":null,"expression":null,"filterable":false,"groupby":false,"is_dttm":null,"type":"DOUBLE","optionName":"_col_value_sum"},"aggregate":"SUM","sqlExpression":null,"hasCustomLabel":false,"fromFormData":false,"label":"SUM(value_sum)","optionName":"metric_3zmf7p8a4g9_p7fsi4zsl1j"}],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"queue_id","operator":"==","comparator":"185","clause":"WHERE","sqlExpression":null,"fromFormData":true,"filterOptionName":"filter_lprl60y1x67_b4zndsnjkx"}],"groupby":["operation"],"columns":[],"row_limit":10000,"contribution":false,"color_scheme":"bnbColors","show_legend":true,"show_bar_value":false,"bar_stacked":false,"order_bars":false,"y_axis_format":".3s","y_axis_label":"","show_controls":false,"x_axis_label":"","bottom_margin":"auto","x_ticks_layout":"auto","reduce_x_ticks":false,"where":"","having":"","having_filters":[],"filters":[{"col":"queue_id","op":"==","val":"185"}]},"is_cached":false,"query":"// Two phase query\n// Phase 1\n{\n  \"queryType\": \"topN\",\n  \"dataSource\": \"visitor-metrics\",\n  \"aggregations\": [\n    {\n      \"fieldName\": \"value_sum\",\n      \"fieldNames\": [\n        \"value_sum\"\n      ],\n      \"type\": \"doubleSum\",\n      \"name\": \"SUM(value_sum)\"\n    }\n  ],\n  \"granularity\": \"all\",\n  \"postAggregations\": [],\n  \"intervals\": \"1970-01-01T00:00:00+00:00/2019-08-27T00:00:00+00:00\",\n  \"filter\": {\n    \"type\": \"selector\",\n    \"dimension\": \"queue_id\",\n    \"value\": \"185\"\n  },\n  \"threshold\": 10000,\n  \"metric\": \"SUM(value_sum)\",\n  \"dimension\": \"operation\"\n}\n// Phase 2 (built based on phase one's results)\n{\n  \"queryType\": \"topN\",\n  \"dataSource\": \"visitor-metrics\",\n  \"aggregations\": [\n    {\n      \"fieldName\": \"value_sum\",\n      \"fieldNames\": [\n        \"value_sum\"\n      ],\n      \"type\": \"doubleSum\",\n      \"name\": \"SUM(value_sum)\"\n    }\n  ],\n  \"granularity\": {\n    \"type\": \"period\",\n    \"timeZone\": \"UTC\",\n    \"period\": \"P1D\"\n  },\n  \"postAggregations\": [],\n  \"intervals\": \"1970-01-01T00:00:00+00:00/2019-08-27T00:00:00+00:00\",\n  \"filter\": {\n    \"type\": \"and\",\n    \"fields\": [\n      {\n        \"type\": \"or\",\n        \"fields\": [\n          {\n            \"type\": \"selector\",\n            \"dimension\": \"operation\",\n            \"value\": \"joining\"\n          }\n        ]\n      },\n      {\n        \"type\": \"selector\",\n        \"dimension\": \"queue_id\",\n        \"value\": \"185\"\n      }\n    ]\n  },\n  \"threshold\": 1000,\n  \"dimension\": \"operation\",\n  \"metric\": \"SUM(value_sum)\"\n}","status":"success","stacktrace":null,"rowcount":1,"data":[{"key":["joining"],"values":[{"x":1566777600000.0,"y":4.0}]}]}
`

my render function

```
 return (
            <Col xs="12" sm="6" lg="3">
                <ChartDataProvider client={SupersetClient} formData={JSON.parse(formData)}>
                    {({ loading, payload, error }) => {
                        if (loading) return <div>Loading!</div>;
                        if (error) return <div>error</div>;
                        if (payload) {
                            return (
                                <SuperChart chartType={'bar'} formData={formData} chartProps={{ formData, payload, width, height }}
                                    onRenderFailure={(data: any) => {
                                        console.log(data)
                                    }} disableErrorBoundary={true} />
                            )
                        }
                    }}
                </ChartDataProvider>
            </Col>
```

no error in the console, In the REACT debugger I can see no component attached after PartentSize 

Can you please suggest what is going wrong?

Thanks,
Rathish

**Comment by yobnytech** [comment]
Thanks @kristw  for the last commit in the NDV3 plugin that was last bit I was struggling as Payload attribute was deprecated.  I believe below is right way to configure the SuperChart component.

```
                            <SuperChart
                                id={"1"}
                                chartType='bar'
                                formData={JSON.parse(formData)}
                                queryData={Array.isArray(payload.queryData) ? payload.queryData[0] : payload.queryData}
                                width={500}
                                height={500} />
```

Now I can generate the required chart, once again thanks for your excellent support and the contribution. I will close this issue. 

![bitmap](https://user-images.githubusercontent.com/46391574/63740318-11340f80-c8ae-11e9-9d67-68988c26293e.png)

**Comment by kalimuthu123** [comment]
Hi in React how to register my plugin there facing lot of issues

![register](https://user-images.githubusercontent.com/42966797/82222258-a98f8a00-993e-11ea-985d-ec4c9713265d.png)
