### ISSUE TITLE
Migrate off react-loadable

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#220]
**Is your feature request related to a problem? Please describe.**

> `react-loadable` was the recommended way for React code splitting for a long time. However, today it is not maintained any more and it is not compatible with Webpack v4+ and Babel v7+.
> If you use it, it is recommended to migrate to React.lazy or @loadable/component.
https://www.smooth-code.com/open-source/loadable-components/docs/loadable-vs-react-lazy/

**Describe the solution you'd like**

Migrate to `React.lazy` or `@loadable/component`.

**Additional context**

`React.lazy` is available since `react@16.6`

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
