### ISSUE TITLE
How can I link superset-ui and Apache-Superset in my development environment.

### ISSUE THREAD

**Issue by zhaoyongjie** [apache-superset/superset-ui#225]
Your question. 
How can I link superset-ui with Apache-superset in my development environment.
use npm, yarn, or lerna?

**Comment by kristw** [comment]
See https://github.com/apache-superset/superset-ui-plugins#activating-plugins-for-local-development

**Comment by zhaoyongjie** [comment]
thank you very much.

**Comment by cdmikechen** [comment]
@kristw Can not find this page, has it been removed?
