### ISSUE TITLE
How to implement default color scheme?

### ISSUE THREAD

**Issue by hurrtz** [apache-superset/superset-ui#237]
Hello everyone,

I am trying to implement a default color scheme that is coming from superset. If, for example, superset returns a query that has `color_scheme: 'bnbColors'` this currently is not used automatically. So I have implemented this manually with

```js
import { getCategoricalSchemeRegistry, CategoricalScheme } from '@superset-ui/color';
import AirBnBColorScheme from '@superset-ui/color/lib/colorSchemes/categorical/airbnb';

getCategoricalSchemeRegistry().registerValue(
  data.form_data.color_scheme, // i.e. bnbColors
  new CategoricalScheme(AirBnBColorScheme)
);
```

But this generates the warning `backend.js:6 Item with key "bnbColors" already exists. You are assigning a new value.`

So: How do I set the color scheme without triggering that warning?

Sadly I can't find any kind of documentation on this matter, hence this question...

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
