### ISSUE TITLE
Use d3 localization for time-format package

### ISSUE THREAD

**Issue by oskarhinc** [apache-superset/superset-ui#238]
**Is your feature request related to a problem? Please describe.**
The date and time presented within the time-format package are not translated for different languages. It could be changed, so the localization would be supported.

**Describe the solution you'd like**
D3 library supports localization, as described  [in the project description](https://github.com/d3/d3-format). The easiest way would be probably changing the default locale at a proper moment. 

**Describe alternatives you've considered**
According to [d3 docs](https://d3-wiki.readthedocs.io/zh_CN/master/Localization/) it is also possible to avoid setting the default locale multiple times, and use proper locale definition when needed, but this might be more complex.

**Comment by cdmikechen** [comment]
I have also encountered this problem, and I am going to analyze superset-ui codes and solve it

**Comment by cdmikechen** [comment]
Can refer to
https://github.com/cdmikechen/incubator-superset/commit/701c844af777e95a7702cfcccf461067598dd78f
https://github.com/cdmikechen/superset-ui/commit/ebec7068f52b6ed9c8ea07fb452fab75d8e994d8 
https://github.com/cdmikechen/superset-ui-plugins/commit/99dcbe594d75190d6dc8ce8402bd27591c235911

Have add a d3locale json to support formatter, and change some functions to adapt to new code

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
