### ISSUE TITLE
How to use with Next.js?

### ISSUE THREAD

**Issue by rrjanbiah** [apache-superset/superset-ui#241]
Has anyone used it in Next.js?

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
