### ISSUE TITLE
Make test in @superset-ui/dimension use fake timers

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#286]
**Is your feature request related to a problem? Please describe.**
Tests are using real timers. If this can be switch to fake timers, it can complete faster.

**Describe the solution you'd like**
Wait time due to real timer is greatly reduced.

**Describe alternatives you've considered**
Now the tests are using real timers and we accept 0.5s wait time for the action to happen before assertion. 

**Additional context**
extracted from #281

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
