### ISSUE TITLE
feat: Add support for storage size formatting

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#320]
**Is your feature request related to a problem? Please describe.**

Formatting storage has different unit: KB, MB, GB, PB...

**Describe the solution you'd like**

A new formatter

**Additional context**
https://github.com/apache/incubator-superset/issues/6916#issuecomment-605132482

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
