### ISSUE TITLE
Using Jinja params every where and not just in raw query views

### ISSUE THREAD

**Issue by jbdoster** [apache-superset/superset-ui#386]
**Is your feature request related to a problem? Please describe.**
No, just a "nice to have"

**Describe the solution you'd like**
Given that I am creating a Superset chart
when I input a custom y axis label string value
then I will use a Jinja parameter I previously set

**Describe alternatives you've considered**
Writing it in

**Additional context**
It'd be cool to use Jinja parameters every where and not just queries, I tried it out but it doesn't seem to work is this possible yet? Thank you!

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
