### ISSUE TITLE
Modify Chord Chart D3 code to fix text labels / import custom Chord diagram

### ISSUE THREAD

**Issue by ghost** [apache-superset/superset-ui#494]
Your question. 
- How do I take chord diagram D3 source code (https://github.com/apache-superset/superset-ui/blob/master/plugins/legacy-plugin-chart-chord/src/Chord.js) that i plan to modify to improve the labeling of the diagram and then build my own custom plugin/chord diagram and use it in my build of superset?  
I've tried following along with how to do this in various scattered github conversations, and I can't seem to find a step-by-step process that is clear (to a data analyst anyway).  Would appreciate any help and willing to talk outside of Github

Thanks

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
