### ISSUE TITLE
SuperChart module error

### ISSUE THREAD

**Issue by kalimuthu123** [apache-superset/superset-ui#498]
i try to use superchart module 

import { SuperChart } from '@superset-ui/chart';
export class Chart extends React.Component {
 render() {
      const { height, width,formdata,payload,CHART_TYPE } = this.state;
      return  (
      <SuperChart type={CHART_TYPE} chartProps={{ formdata, payload, width, height }} />
      );
    }
but  when i add data to the values  i am facing some issues
![error](https://user-images.githubusercontent.com/42966797/82198846-8652e380-991a-11ea-939d-5c79bf31940d.png)

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
