### ISSUE TITLE
Apache Superset error - <html><body><h1>504 Gateway Time-out</h1> The server didn't respond in time. </body></html>

### ISSUE THREAD

**Issue by aamir306** [apache-superset/superset-ui#537]
can I increase this 1-minute limit for the queries? It is very annoying. Every time I run larger queries, it timeout. can anybody help on this? I have already set SUPERSET_WEBSERVER_TIMEOUT to 3600. Why this is happening?

[Error screenshot](https://i.stack.imgur.com/ChJJM.png)

**Comment by mistercrunch** [comment]
I think your web server, proxy or something else in your request path is timing out.

**Comment by mistercrunch** [comment]
You want to set your `SUPERSET_WEBSERVER_TIMEOUT` to be lower than your smallest timeout in your query path.

**Comment by fgomezotero** [comment]
Hello everyone!

I have the same problem for long queries. Searching I found a forum that recommends increasing the timeout parameter in gunicorn, I set 120 seconds but this does not solve the problem. It still keeps happening

Superset version: 1.1.0

Regards

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
