### ISSUE TITLE
Calendar Heatmap linear color scheme values distribution problem

### ISSUE THREAD

**Issue by eohulse** [apache-superset/superset-ui#538]
The linear color scheme of the calendar heatmap is not using the maximum and minimum values that are displayed in the calendar to assign the color of each calendar cell.

**To Reproduce**
The problem can be reproduced in any calendar heatmap that is created

**Expected behavior**
The linear color scheme should use the maximum and minimum values in the set to be displayed to create the color scheme distribution.

**Screenshots**
This screenshot shows an example where values go from 1 to 10, but the color scheme is set from 1 to 3.
![image](https://user-images.githubusercontent.com/7784632/82902738-4d2bfc00-9f36-11ea-90a5-edcccb2ef3fa.png)

**Superset version**
0.36.0

**Comment by eohulse** [comment]
My guess is that the problem is in superset-ui/plugins/legacy-plugin-chart-calendar/src/Calendar.js
In the line 118 where it is coded:

const step = (extents[1] - extents[0]) / (steps - 1);

it should be something like:

const step = (extents[extents.length - 1] - extents[0]) / (steps - 1);

**Comment by eohulse** [comment]
It seems that the bug is happening when it is trying the get the maximum and minimum values from each metric.

In [Calendar.js](https://github.com/apache-superset/superset-ui/blob/master/plugins/legacy-plugin-chart-calendar/src/Calendar.js), line 118,
> const extents = d3Extent(Object.keys(timestamps), key => timestamps[key]);
seem not to be returning the minimum and maximum values that will appear in the calendar for each metric.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
