### ISSUE TITLE
feat(plugin-chart-choropleth-map): smooth zooming

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#550]
**Describe the solution you'd like**

Transition when zoom in/out

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
