### ISSUE TITLE
not a valid react native component!

### ISSUE THREAD

**Issue by kalimuthu123** [apache-superset/superset-ui#568]
Hi ,

   when i tried to embed the "superchart" Component in the react native app
the failure occurs in the following error

Invariant Violation : View config not found for name div :Make sure to start a component name with a capital letter
            This error is located at :   
                          in div (created by SuperChartCore)
                          in  SuperChartCore  (created by SuperChart)
                   <div>div</div> is an invalid React Native Component

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
