### ISSUE TITLE
about translation

### ISSUE THREAD

**Issue by byc233518** [apache-superset/superset-ui#58]
Your question. 
- How do I use translation in chart component?

thanks!

**Comment by mistercrunch** [comment]
@kristw @williaster never thought of that much, but where will translations live in/around `superset-ui` ?

**Comment by williaster** [comment]
checkout [`@superset-ui/translation`](https://github.com/apache-superset/superset-ui/tree/master/packages/superset-ui-translation)

The readme there should help you out but feel free to re-open this if not.

**Comment by williaster** [comment]
for a bit more clarification, to use this **in** a chart component would mean that the chart has to support a hook for it, and in that case you would then wrap anything that generated text in the translation calls. 

however, we don't quite have the charts added to `superset-ui` yet, so this isn't technically possible. it's also not clear to me that all charts currently support this 🤔 but we can keep it in mind as we move charts from the Superset app into `superset-ui` plugins.

cc @kristw @xtinec @conglei

**Comment by mistercrunch** [comment]
I'm thinking about the discovery part of it where `babel` (the python i18n package) parses the code to find strings to add to the dict of things to translate. I'm thinking that when we move the charts over to the `superset-ui` repo, `babel` won't discover them anymore. 

We may need some sort of git submodule setup or symlink for this purpose. I don't think it's super hard to do, but something to think about.

**Comment by williaster** [comment]
Oh interesting. yeah maybe when we move charts here we can investigate this more. 

when does the python `babel` run / how long does it take? another option could possibly be to add a step during `npm install` and add an analysis of the `node_modules/@superset-ui` modules.

**Comment by mistercrunch** [comment]
Here's where/how the strings get extracted for translation: https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#extracting-new-strings-for-translation

I like the idea of idea `node_modules/superset-ui` to the whitelist
