### ISSUE TITLE
remove `diff hit` threshold

### ISSUE THREAD

**Issue by williaster** [apache-superset/superset-ui#6]
Described in #6 [here](https://github.com/apache-superset/superset-ui/pull/5#issuecomment-422241285)
> I will also fix the `90.9% of diff hit` issue in another PR. there is still `98.5%` coverage after this PR, I think the percentage of the lines changed in a PR is not as relevant and the threshold should be on total coverage %.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
