### ISSUE TITLE
Simplify SupersetClient singleton

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#64]
**Is your feature request related to a problem? Please describe.**
`SupersetClient` wrapper creates overhead in maintaining another type and cause confusion as there is the original class and the wrapper.

**Describe the solution you'd like**
Use same pattern with other singletons, but may involves breaking change to how to get the singleton which affects `incubator-superset`

**Describe alternatives you've considered**
Keep it like this

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
