### ISSUE TITLE
Error adding a plugin in 0.36.0 release of incubator-superset

### ISSUE THREAD

**Issue by Agustin6199** [apache-superset/superset-ui#710]
Hi! Im getting an error when I try to deploy Superset because of a plugin I tried to add. 

I was looking for adding new visualizations to Apache Superset, so I followed the steps u can find [here](https://preset.io/blog/2020-07-02-hello-world/) to create a plugin of a horizontal barplot by running a Yeoman generator.

As the blog says, I generated all the files with the generator and then I added the plugin to Superset. To add the plugin to Superset I added my package to the `package.json` in `incubator-superset/superset-frontend`, then I also added my plugin to the `MainPreset.js` in  `incubator-superset/superset-frontend/src/visualizations/presets/MainPreset.js`. The last thing I did was using `npm link` to symlink the plugin using a relative path to the plugin folder.

It should work, but when I deploy my app with `docker-compose up` I get an error because my plugin isnt in the npm registry. I dont know why is searching my plugin on the npm registry. Heres a screenshot from the error while deploying.

![Captura de pantalla de 2020-07-27 12-11-05](https://user-images.githubusercontent.com/55829168/88530884-530b8f80-d002-11ea-90ee-e6459169c4d5.png)

I would like to know why is this happening, and how to solve it to deploy my app with the added plugin.

I am on 0.36.0 release of incubator-superset.

**Comment by amitNielsen** [comment]
@Agustin6199 I don't think new viz plugin  is supported on 0.36 you should move to 0.37 branch for sure

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
