### ISSUE TITLE
Table chart metric header right align

### ISSUE THREAD

**Issue by stuarthu** [apache-superset/superset-ui#719]
**Is your feature request related to a problem? Please describe.**
Table chart metric number is right aligned, but the header is not.

**Describe the solution you'd like**
Metric header is right aligned

**Describe alternatives you've considered**
Alternatively, we can make metric number left aligned.

**Additional context**
# Expect result:
![截屏2020-07-31 11 56 51](https://user-images.githubusercontent.com/16526001/88998605-ffac8080-d324-11ea-84c2-fa641e982877.png)

**Comment by mistercrunch** [comment]
For consistency I think all headers should be left aligned and the sort icons should be right next to the header works.

**Comment by ktmud** [comment]
> For consistency I think all headers should be left aligned and the sort icons should be right next to the header works.

Numeric values are easier to read when right aligned. You may find the same design principle in [various](https://design.mindsphere.io/patterns/table.html#tab1anchor5) [design](https://alistapart.com/article/web-typography-tables/#section5) [guides](https://medium.com/mission-log/design-better-data-tables-430a30a00d8c).

I'll make the header for table right aligned (or a pull request is also welcome).

**Comment by stuarthu** [comment]
I tried to bring a PR but that is beyond my skills.

**Comment by stuarthu** [comment]
fixed in https://github.com/apache-superset/superset-ui/pull/721
