### ISSUE TITLE
make `release` script compatible with forks

### ISSUE THREAD

**Issue by williaster** [apache-superset/superset-ui#73]
**Describe the bug**
The current `lerna` `release` script was written assuming that the `origin` branch is the primary `apache-superset/superset-ui` repo, as opposed to a fork. This is problematic because

- forks may not be up to date with `apache-superset/superset-ui`
- publishing pushes tags and package version number changes to the _fork_ instead of `apache-superset/superset-ui`, requiring a second PR to update the main repo.

cc @kristw @soboko @xtinec @conglei

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
