### ISSUE TITLE
chart-table format empty string into 0NaN-NaN-NaN NaN:NaN:NaN

### ISSUE THREAD

**Issue by stuarthu** [apache-superset/superset-ui#731]
**Describe the bug**
I have a table with a column of type string.
Most times, the value of the column is a string like `"2020-08-04 06:01:31"` but sometimes it is an empty string "".
I don't want to format it as datetime so especially set that column flag `Is temporal` to false.
![截屏2020-08-11 18 41 53](https://user-images.githubusercontent.com/16526001/89888357-6aea3280-dc02-11ea-8693-3ed247411013.png)

But chart-table still render those empty string to "0NaN-NaN-NaN NaN:NaN:NaN"
![截屏2020-08-11 18 23 27](https://user-images.githubusercontent.com/16526001/89888402-776e8b00-dc02-11ea-93d3-b10f9e8b8b51.png)

This is because in `superset-ui/plugins/plugin-chart-table/srctransformProps.ts`, we use `REGEXP_DATETIME` to determine if a string type column is a datetime type.

**Expected behavior**
We should only use `Is temporal` flag rather than REGEXP_DATETIME to determine whether a column is datetime type.
If a column has flag `Is temporal` = false, superset should not render it as datetime.

**Environment (please complete the following information):**
 - superset-ui version: [v0.14.20]

**Comment by stuarthu** [comment]
@ktmud

**Comment by stuarthu** [comment]
I was able to bring a PR: https://github.com/apache-superset/superset-ui/pull/733
Which only removes `REGEXP_DATETIME`.
It can parse the column correctly for empty string value.

**Comment by stevensuting** [comment]
+1

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
