### ISSUE TITLE
How to add a new plugin which was rendered by python?

### ISSUE THREAD

**Issue by Sherhang** [apache-superset/superset-ui#740]
I tried to add a new chart plugin to superset0.37, and I write a  new chart class in superset/viz.py. 
However, the new chart class did not work. It only excutes the fronted codes，ignoring the python code.
In terminal, the INFO is 
```
 INFO:superset.common.query_context:Cache key: e4fd71cd0177306d5ec282c473eb6b81
```
I hope it runs in superset.viz as below:
```
INFO:superset.viz:Cache key: 3ab3562d5bc67fef2760f0ddd1307fc5
```
What should I do?

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
