### ISSUE TITLE
feat(bar): sort superset bar charts by bar values

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#741]
**Is your feature request related to a problem? Please describe.**

> I have a bar chart in Superset that I'd like to sort by bar values (descending order). But the default is to sort the bars by alphabetical order, is there any way to get around this?

-- Airbnb user

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
