### ISSUE TITLE
Line chart does not render results when there is only one timestamp

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#742]
**Describe the bug**

> A chart that only contains one day of data. The data points are not rendered on the chart unless you magically hover where they are (see attached screenshot).
> I realize that this is a "line" chart but my sense is it should render points when appropriate.
> -- A user

**To Reproduce**
Create a line chart and filter to a single day of data.

![Pasted_Image_8_17_20__5_46_PM](https://user-images.githubusercontent.com/1659771/90457901-ab89f600-e0b1-11ea-82aa-ba37970f3d81.png)

**Comment by mistercrunch** [comment]
What is the "line" chart supposed to do? Be a "dot" chart?

**Comment by kristw** [comment]
> What is the "line" chart supposed to do? Be a "dot" chart?

lol. I was thinking about addressing by adding error message for this case.

**Comment by kristw** [comment]
Umm, actually ECharts handle this quite well by centering the point. I think I am going to close this and wait for the echart plugin

![image](https://user-images.githubusercontent.com/1659771/90559177-18ed6380-e152-11ea-9209-67020af2f27f.png)
