### ISSUE TITLE
Pivot chart does not correctly display D3 formats on large numbers

### ISSUE THREAD

**Issue by rea725** [apache-superset/superset-ui#745]
### Expected results

D3 formats should be applied across all charting objects consistently.

For example: 
A number of 10000.44444 formatted with D3 format $,.4f should result in the number being rendered as $10,000.4444.

### Actual results

D3 formats are working properly in the "Table" chart object, but working incorrectly in the "Pivot" chart object.

Specifically, rounding is not working correctly in the pivot chart object.  It appears that a bug exists which causes the significant digits to be limited to 7.

For example, consider a number of 10000.44444 formatted with D3 format $,.4f.

This is displayed as $10,000.4444 in a Superset table chart. This is correct.
This is displayed as $10,000.4400 in a Superset pivot chart. This is incorrect.

#### Screenshots
![image](https://user-images.githubusercontent.com/276963/90680160-668bce00-e22f-11ea-8779-0cc96857d0eb.png)

#### How to reproduce the bug
**Option A:**
1. Go to [superset.plaidcloud.io](superset.plaidcloud.io)
2. Sign in with user: `admin`, password: `admin`
3. Open dashboard called `ROUNDING_BUG_REPORT`.
4. Observe issues in ROUNDING_PIVOT_BUG chart in the dashboard.  

**Option B:**
Alternatively, this can be re-created from scratch using the attached data and included Superset dashboard.
[round_bug_data_and_dashboard.zip](https://github.com/apache/incubator-superset/files/5098838/round_bug_data_and_dashboard.zip)

**Option C:**
Use any dataset with values that are adequately large (> 10,000) and at least four significant digits to the right of the decimal.  Create a calculated metric based on the value, and apply a D3 format such as $,.4f.

### Environment

- superset version: `preset/superset:0071d374daf37caf53f67c287e8774ab984c611b`
- python version: `3.6.3`
- We are using the pre-built preset images to reproduce.  Thus, npm and node are not installed.
![image](https://user-images.githubusercontent.com/276963/90681233-144bac80-e231-11ea-96dd-daeff9a1b232.png)

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by inviscid** [comment]
This is a reproducible bug that can cause some nasty side effects with large numbers being rounded.  Any chance someone could look at this soon?

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
