### ISSUE TITLE
 Big number chart appears a fronted error when is rendering 

### ISSUE THREAD

**Issue by pwj126** [apache-superset/superset-ui#753]
**Describe the bug**
TypeError: Cannot read property 'families' of undefined

**To Reproduce**
1. Go to our charts page 
2. Click on a button to render a Big number
3. Scroll down to see my code and my dependencies
(1) my code 
```jsx
<SuperChart
      key={`${chartId}`}
      id={`chart-id-${chartId}`}
      chartType={type}
      width={400}
      height={400}
      formData={{
               colorPicker: {
                 a: 1,
                 b: 135,
                 g: 122,
                 r: 0
               },
               compareLag: 1,
               compareSuffix: 'over 10Y',
               metric: 'sum__SP_POP_TOTL',
               showTrendLine: true,
               startYAxisAtZero: true,
               vizType: 'big_number',
               yAxisFormat: '.3s'
             }}
      queryData={{
               data: [
                 {
                   __timestamp: 1388534400000,
                   sum__SP_POP_TOTL: 7237260256
                 },
                 {
                   __timestamp: 1356998400000,
                   sum__SP_POP_TOTL: 7151135481
                 },
                 {
                   __timestamp: 1325376000000,
                   sum__SP_POP_TOTL: 7066007165
                 },
                 {
                   __timestamp: 1293840000000,
                   sum__SP_POP_TOTL: 6984252419
                 },
                 {
                   __timestamp: 1262304000000,
                   sum__SP_POP_TOTL: 6901110512
                 },
                 {
                   __timestamp: 1230768000000,
                   sum__SP_POP_TOTL: 6818457192
                 },
                 {
                   __timestamp: 1199145600000,
                   sum__SP_POP_TOTL: 6735914031
                 },
                 {
                   __timestamp: 1167609600000,
                   sum__SP_POP_TOTL: 6653571302
                 },
                 {
                   __timestamp: 1136073600000,
                   sum__SP_POP_TOTL: 6572596462
                 },
                 {
                   __timestamp: 1104537600000,
                   sum__SP_POP_TOTL: 6491857539
                 },
                 {
                   __timestamp: 1072915200000,
                   sum__SP_POP_TOTL: 6411615629
                 },
                 {
                   __timestamp: 1041379200000,
                   sum__SP_POP_TOTL: 6331766837
                 },
                 {
                   __timestamp: 1009843200000,
                   sum__SP_POP_TOTL: 6252469127
                 },
                 {
                   __timestamp: 978307200000,
                   sum__SP_POP_TOTL: 617333941
                 }
               ]
             }}
    />
```
(2) my dependencies
    "@superset-ui/chart": "^0.14.0",
    "@superset-ui/chart-controls": "^0.14.0",
    "@superset-ui/color": "^0.14.0",
    "@superset-ui/core": "^0.14.0",
    "@superset-ui/dimension": "^0.14.0",
    "@superset-ui/number-format": "^0.14.0",
    "@superset-ui/style": "^0.14.0",
    "@superset-ui/time-format": "^0.14.0",
    "@superset-ui/translation": "^0.14.0",
    "@superset-ui/connection": "^0.14.0",
    "@superset-ui/query": "^0.14.0",
    "@superset-ui/validator": "^0.14.0",
    "@superset-ui/legacy-preset-chart-big-number": "^0.14.9"

Oops! An error occured!
TypeError: Cannot read property 'families' of undefined

**Expected behavior**
The Big number chart can be rendered correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/8382753/91247987-2aec8900-e786-11ea-8c93-6d3c53d9f048.png)
.

**Environment (please complete the following information):**
 - superset-ui version: [0.14.0]
 - Node version: `node - v10.16.0`
 - npm version: `npm -v6.9.0`
 
**Additional context**
I plan to use plugins of SuperSet-ui for my projects

**Comment by rusackas** [comment]
@pjw126 are you using `SuperChart` and `superset-ui` outside of Superset, in some other codebase? If so, I think I may have the info you need... 

This bug about `families` is the plugin trying to find `theme.typography.families` which is an Emotion theme passed into plugins by Superset. `theme` defaults to an empty object when not passed in, thus the error you see. In your react app(s), you can:
`import { supersetTheme, ThemeProvider } from '@superset-ui/style';` 
then wrap your App (or whatever) in them like so:
```
<ThemeProvider theme={supersetTheme}>
  <YourApp>
    <SuperChart ...>
    ...
  </YourApp>
</ThemeProvider>
```

**Comment by pwj126** [comment]
Thank you Mr rusackas, my Big Number Chart can be render correctly.
Then, I plan to use  the plugins of  Superset-ui,  could you provide the detailed user's manual how to use every plugin outside of Superset

**Comment by rusackas** [comment]
Hi @pwj126 Sorry for the delayed reply. I don't know of any user docs on using superset-ui plugins outside of Superset. In fact, I've never personally tried it. I'd love to hear mroe about your use case so i can help to support it if it's a potentially common one. I believe @kristw has some insight into how to use these plugins in other projects, and may be able to provide some small amount of help. That said, I'm wondering if the <ThemeProvider> tip is enough to mark this particular bug as resolved.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
