### ISSUE TITLE
Area Chart appears error when it is rendered

### ISSUE THREAD

**Issue by pwj126** [apache-superset/superset-ui#763]
Your question. 
- when I use the plugins in @superset-ui/legacy-preset-chart-nvd3, for example,  Area Chart is registered as same as big_number , but it appear error: ERROR chartType="area" —Error: Item with key "area" is not registered. Please what reason is it?

**Comment by LikithChintala** [comment]
@pwj126 im getting the same error for bignumber did you found the way

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
