### ISSUE TITLE
The @superset-ui many  modules are missing I18N files

### ISSUE THREAD

**Issue by toop** [apache-superset/superset-ui#765]
### Expected results
When you click the language button, the text on the Explore page switches to the current language。
example：
“Predictive Analytics” -->" 预测分析"
"ENABLE FORECAST" --> "启用预测"
"FORECAST PERIODS" --> "预测期间"

### Actual results
There was no change。

### Screenshots
![image](https://user-images.githubusercontent.com/1625023/91965859-a8df0000-ed43-11ea-815d-2c88379bb39d.png)

### How to reproduce the bug
Login superset
Go to Explore page
Click the switch language button
See error
### Environment
superset version: master
python version: 3.7.7
node.js version: 12.16.2
npm version: 6.14.4 

### but fab babel-extract not generated to file messages.po，How to build the i18n.ts or i18n.js ? help pls！Thanks！

**Comment by JunlinC** [comment]
🏷localization

**Comment by willbarrett** [comment]
@rusackas do you have insight on how i18n builds work here?

**Comment by toop** [comment]
l writed i18n.js like the examples，it·s worked。
