### ISSUE TITLE
Sunburst color palette readability issue

### ISSUE THREAD

**Issue by ktmud** [apache-superset/superset-ui#784]
**Describe the bug**

Sunburst charts sometimes have white text on light brackground.

![image (1)](https://user-images.githubusercontent.com/335541/92968123-61393200-f42f-11ea-98c7-38c49cd2a99b.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - superset-ui version: [e.g. v0.5.0]
 - Node version: `node -v`
 - npm version: `npm -v`
 
**Additional context**

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
