### ISSUE TITLE
Failed when adding a new chart plugin generated from yoeman and superset-generator

### ISSUE THREAD

**Issue by Musa10** [apache-superset/superset-ui#792]
I followed the same steps in the following link : 
https://preset.io/blog/2020-07-02-hello-world/
but i have this error when running 'npm run build'

```
ERROR in ./src/visualizations/presets/MainPreset.js
Module not found: Error: Can't resolve '@superset-ui/plugin-chart-echarts' in '/home/musa/Desktop/projects/incubator-superset/superset-frontend/src/visualizations/presets'

ERROR in chunk addSlice [entry]
addSlice.744a371a6089fefb8a04.entry.js
/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/thread-loader/dist/cjs.js!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/babel-loader/lib/index.js??ref--5-1!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/ts-loader/index.js??ref--5-2!/home/musa/Desktop/projects/incubator-superset/superset-frontend/src/setup/setupPlugins.ts 65af881bb3441c009c04aa245b6caaf2
Unexpected token (74:10)
|       new __WEBPACK_MODULE_REFERENCE__43_64656661756c74__().configure({ key: 'directed_force' }),
|       new __WEBPACK_MODULE_REFERENCE__47_64656661756c74__().configure({ key: 'heatmap' }),
|       new !(function webpackMissingModule() { var e = new Error("Cannot find module '@superset-ui/plugin-chart-echarts'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())().configure({ key: 'hello_world' }),
|       new __WEBPACK_MODULE_REFERENCE__51_64656661756c74__().configure({ key: 'histogram' }),
|       new __WEBPACK_MODULE_REFERENCE__55_64656661756c74__().configure({ key: 'horizon' }),

ERROR in chunk crudViews [entry]
crudViews.27b87d96cc5018f420c4.entry.js
/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/thread-loader/dist/cjs.js!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/babel-loader/lib/index.js??ref--5-1!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/ts-loader/index.js??ref--5-2!/home/musa/Desktop/projects/incubator-superset/superset-frontend/src/setup/setupPlugins.ts 65af881bb3441c009c04aa245b6caaf2
Unexpected token (74:10)
|       new __WEBPACK_MODULE_REFERENCE__43_64656661756c74__().configure({ key: 'directed_force' }),
|       new __WEBPACK_MODULE_REFERENCE__47_64656661756c74__().configure({ key: 'heatmap' }),
|       new !(function webpackMissingModule() { var e = new Error("Cannot find module '@superset-ui/plugin-chart-echarts'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())().configure({ key: 'hello_world' }),
|       new __WEBPACK_MODULE_REFERENCE__51_64656661756c74__().configure({ key: 'histogram' }),
|       new __WEBPACK_MODULE_REFERENCE__55_64656661756c74__().configure({ key: 'horizon' }),

ERROR in chunk dashboard [entry]
dashboard.a86e31392dbd9a2be69f.entry.js
/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/thread-loader/dist/cjs.js!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/babel-loader/lib/index.js??ref--5-1!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/ts-loader/index.js??ref--5-2!/home/musa/Desktop/projects/incubator-superset/superset-frontend/src/setup/setupPlugins.ts 65af881bb3441c009c04aa245b6caaf2
Unexpected token (74:10)
|       new __WEBPACK_MODULE_REFERENCE__43_64656661756c74__().configure({ key: 'directed_force' }),
|       new __WEBPACK_MODULE_REFERENCE__47_64656661756c74__().configure({ key: 'heatmap' }),
|       new !(function webpackMissingModule() { var e = new Error("Cannot find module '@superset-ui/plugin-chart-echarts'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())().configure({ key: 'hello_world' }),
|       new __WEBPACK_MODULE_REFERENCE__51_64656661756c74__().configure({ key: 'histogram' }),
|       new __WEBPACK_MODULE_REFERENCE__55_64656661756c74__().configure({ key: 'horizon' }),

ERROR in chunk explore [entry]
explore.0a9a6b2b7add0423e030.entry.js
/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/thread-loader/dist/cjs.js!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/babel-loader/lib/index.js??ref--5-1!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/ts-loader/index.js??ref--5-2!/home/musa/Desktop/projects/incubator-superset/superset-frontend/src/setup/setupPlugins.ts 65af881bb3441c009c04aa245b6caaf2
Unexpected token (74:10)
|       new __WEBPACK_MODULE_REFERENCE__43_64656661756c74__().configure({ key: 'directed_force' }),
|       new __WEBPACK_MODULE_REFERENCE__47_64656661756c74__().configure({ key: 'heatmap' }),
|       new !(function webpackMissingModule() { var e = new Error("Cannot find module '@superset-ui/plugin-chart-echarts'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())().configure({ key: 'hello_world' }),
|       new __WEBPACK_MODULE_REFERENCE__51_64656661756c74__().configure({ key: 'histogram' }),
|       new __WEBPACK_MODULE_REFERENCE__55_64656661756c74__().configure({ key: 'horizon' }),
```

**Comment by rusackas** [comment]
Something looks a little off about this part of the error:
```
| new !(function webpackMissingModule() { var e = new Error("Cannot find module '@superset-ui/plugin-chart-echarts'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())().configure({ key: 'hello_world' }),
```
Can you make sure that in MainPreset.js you have the following two edits made to look like they do here?

![image](https://user-images.githubusercontent.com/812905/93845927-6714eb80-fc57-11ea-86f8-889a8e5c6e7c.png)

... it looks as though you might have the key "hello_world" applied to the `plugin-chart-echarts` plugin

**Comment by Musa10** [comment]
i am sorry i was testing if it works in another  charts....here is the error:
> superset@0.999.0-dev build /home/musa/Desktop/projects/incubator-superset/superset-frontend
> cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors

Starting type checking service...
Using 1 worker with 2048MB memory limit
92% chunk asset optimization OptimizeCssAssetsWebpackPluginBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
   6036 modules

ERROR in ./src/visualizations/presets/MainPreset.js
Module not found: Error: Can't resolve '@superset-ui/plugin-chart-hello-world' in '/home/musa/Desktop/projects/incubator-superset/superset-frontend/src/visualizations/presets'

ERROR in chunk addSlice [entry]
addSlice.fa3e9fe675025bdb0397.entry.js
/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/thread-loader/dist/cjs.js!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/babel-loader/lib/index.js??ref--5-1!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/ts-loader/index.js??ref--5-2!/home/musa/Desktop/projects/incubator-superset/superset-frontend/src/setup/setupPlugins.ts b4dc456f4c992a12e66971a42a0f993f
Unexpected token (74:10)
|       new __WEBPACK_MODULE_REFERENCE__43_64656661756c74__().configure({ key: 'directed_force' }),
|       new __WEBPACK_MODULE_REFERENCE__47_64656661756c74__().configure({ key: 'heatmap' }),
|       new !(function webpackMissingModule() { var e = new Error("Cannot find module '@superset-ui/plugin-chart-hello-world'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())().configure({ key: 'hello_world' }),
|       new __WEBPACK_MODULE_REFERENCE__51_64656661756c74__().configure({ key: 'histogram' }),
|       new __WEBPACK_MODULE_REFERENCE__55_64656661756c74__().configure({ key: 'horizon' }),

ERROR in chunk crudViews [entry]
crudViews.fa84b5f1276da7109d9a.entry.js
/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/thread-loader/dist/cjs.js!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/babel-loader/lib/index.js??ref--5-1!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/ts-loader/index.js??ref--5-2!/home/musa/Desktop/projects/incubator-superset/superset-frontend/src/setup/setupPlugins.ts b4dc456f4c992a12e66971a42a0f993f
Unexpected token (74:10)
|       new __WEBPACK_MODULE_REFERENCE__43_64656661756c74__().configure({ key: 'directed_force' }),
|       new __WEBPACK_MODULE_REFERENCE__47_64656661756c74__().configure({ key: 'heatmap' }),
|       new !(function webpackMissingModule() { var e = new Error("Cannot find module '@superset-ui/plugin-chart-hello-world'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())().configure({ key: 'hello_world' }),
|       new __WEBPACK_MODULE_REFERENCE__51_64656661756c74__().configure({ key: 'histogram' }),
|       new __WEBPACK_MODULE_REFERENCE__55_64656661756c74__().configure({ key: 'horizon' }),

ERROR in chunk dashboard [entry]
dashboard.76a3b269f5ab1cc704e6.entry.js
/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/thread-loader/dist/cjs.js!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/babel-loader/lib/index.js??ref--5-1!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/ts-loader/index.js??ref--5-2!/home/musa/Desktop/projects/incubator-superset/superset-frontend/src/setup/setupPlugins.ts b4dc456f4c992a12e66971a42a0f993f
Unexpected token (74:10)
|       new __WEBPACK_MODULE_REFERENCE__43_64656661756c74__().configure({ key: 'directed_force' }),
|       new __WEBPACK_MODULE_REFERENCE__47_64656661756c74__().configure({ key: 'heatmap' }),
|       new !(function webpackMissingModule() { var e = new Error("Cannot find module '@superset-ui/plugin-chart-hello-world'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())().configure({ key: 'hello_world' }),
|       new __WEBPACK_MODULE_REFERENCE__51_64656661756c74__().configure({ key: 'histogram' }),
|       new __WEBPACK_MODULE_REFERENCE__55_64656661756c74__().configure({ key: 'horizon' }),

ERROR in chunk explore [entry]
explore.f88e321328f7da8a906b.entry.js
/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/thread-loader/dist/cjs.js!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/babel-loader/lib/index.js??ref--5-1!/home/musa/Desktop/projects/incubator-superset/superset-frontend/node_modules/ts-loader/index.js??ref--5-2!/home/musa/Desktop/projects/incubator-superset/superset-frontend/src/setup/setupPlugins.ts b4dc456f4c992a12e66971a42a0f993f
Unexpected token (74:10)
|       new __WEBPACK_MODULE_REFERENCE__43_64656661756c74__().configure({ key: 'directed_force' }),
|       new __WEBPACK_MODULE_REFERENCE__47_64656661756c74__().configure({ key: 'heatmap' }),
|       new !(function webpackMissingModule() { var e = new Error("Cannot find module '@superset-ui/plugin-chart-hello-world'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())().configure({ key: 'hello_world' }),
|       new __WEBPACK_MODULE_REFERENCE__51_64656661756c74__().configure({ key: 'histogram' }),
|       new __WEBPACK_MODULE_REFERENCE__55_64656661756c74__().configure({ key: 'horizon' }),
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! superset@0.999.0-dev build: `cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/musa/.npm/_logs/2020-09-22T12_00_29_370Z-debug.log

**Comment by Musa10** [comment]
![Screenshot from 2020-09-22 14-53-52](https://user-images.githubusercontent.com/47694350/93879639-bbb27800-fce4-11ea-8b8c-f9c47e3a4133.png)
![Screenshot from 2020-09-22 14-54-02](https://user-images.githubusercontent.com/47694350/93879646-bead6880-fce4-11ea-960f-2692be8dfa83.png)

**Comment by Musa10** [comment]
first of all...the instructions in the website are missing an important step...the 'Hello-world' build should be done in superset-ui..after creating the plugin:
-cd superset-ui
-yarn build (use only yarn,npm giving errors ,I don't know why)
-cd plugins/plugin-chart-hello-world
-yarn link
-cd incubator-superset/superset-frontend
-yarn link '@superset-ui/plugin-chart-hello-world'
..................................................................................
include the package in superset-front-end/packge.json && superset-frontend/visualization/preset/MainPreset and then run yarn dev-server...yarn build should work too
