### ISSUE TITLE
Superset-ui v0.15.3 with incubator-superset fails with generator-superset 0.15.3

### ISSUE THREAD

**Issue by codepic** [apache-superset/superset-ui#793]
**Describe the bug**
Hello world plugin generated with  generator-superset 0.15.3 won't run properly with superset incubator-superset.

The process is pretty much the same as in [So, You Want to Build a Superset Viz Plugin...](https://preset.io/blog/2020-07-02-hello-world/)

Have tried with (incubator-superset)
- current master (9d7b3536e11ba550467b3872f0b0d56e865cf1c9)
- 0.37.1
- 0.37.2rc2
- 0.38 (f7e2dfa6056acf83b8a32bd1745e03c33d25047b)

**To Reproduce**

### Setup repro

```bash
# Setup root dir for repro
export SUPERSET_REPRO_ROOT=~/Desktop/superset_repro
export SUPERSET_REF=0.37.1
export SUPERSET_SHA=fa787d2de40a9bf90cf2f365bbc7a75b92227bcd
export SUPERSET_UI_VERSION=v0.15.3
cd $SUPERSET_REPRO_ROOT

# Clean up any potential docker resources
docker ps -q --filter name='superset' | xargs -r docker stop
docker ps -q --filter name='superset' | xargs -r docker rm
echo 'y' |docker container prune
echo 'y' |docker volume prune
echo 'y' |docker network prune

# Remove existing folders (sometimes requires sudo)
rm -rf $SUPERSET_REPRO_ROOT/incubator-superset
rm -rf $SUPERSET_REPRO_ROOT/superset-ui
```

### Pull and run superset

```bash
# Get superset up and running
cd $SUPERSET_REPRO_ROOT
git clone -b $SUPERSET_REF https://github.com/apache/incubator-superset.git
cd $SUPERSET_REPRO_ROOT/incubator-superset
git checkout $SUPERSET_REF --force
git pull
git reset --hard $SUPERSET_SHA
docker-compose up --build
```

After this I check that the http://localhost:8088 runs normally without errors.

### New terminal: Run superset-frontend
```bash
## Install 
cd $SUPERSET_REPRO_ROOT/incubator-superset/superset-frontend
npm install
npm run dev-server
```

After this I check that the http://localhost:9000 runs normally without errors.

## Create a new plugin

```bash
# Clone superset-ui
cd $SUPERSET_REPRO_ROOT
git clone -b $SUPERSET_UI_VERSION https://github.com/apache-superset/superset-ui.git

# Set up the new plugin with generator-superset
cd $SUPERSET_REPRO_ROOT/superset-ui
yarn install
cd $SUPERSET_REPRO_ROOT/superset-ui/plugins
mkdir plugin-chart-hello-world
cd plugin-chart-hello-world
npm install -g yo @superset-ui/generator-superset@$SUPERSET_UI_VERSION
yo @superset-ui/superset
```

### Answer the following:
```
? What do you want to do? Create superset-ui chart plugin package
? Package name: hello-world
? Description: Hello World
? What type of React component would you like? Class component
? What type of chart would you like? Time-series chart
? Add superset-ui badges to your plugin's README.md Yes
```

### Add tsconfig.json to the current folder and give it the following content

```
{
  "compilerOptions": {
    "declarationDir": "lib",
    "outDir": "lib"
  },
  "exclude": [
    "lib",
    "test"
  ],
  "extends": "../../tsconfig.options.json",
  "include": [
    "src/**/*",
    "types/**/*",
    "../../types/**/*"
  ]
}
```

## Add the following to incubator-superset/superset-frontend/package.json dependencies section

```
    "@superset-ui/plugin-chart-hello-world": "^0.0.0",
```

## Add the following to incubator-superset/superset-frontend/src/visualizations/presets/MainPreset.js

```js
// Before FilterBoxChartPlugin
import HelloWorldChartPlugin from '@superset-ui/plugin-chart-hello-world';
```

```js
// After EchartsTimeseriesChartPlugin

new HelloWorldChartPlugin().configure({
    key: 'hello-world'
})

```

## Execute the following in a new terminal
```bash
cd $SUPERSET_REPRO_ROOT/incubator-superset/superset-frontend
npm link ../../superset-ui/plugins/plugin-chart-hello-world
```

## restart dev-server
```bash
cd $SUPERSET_REPRO_ROOT/incubator-superset/superset-frontend
npm run dev-server
```

The terminal shows the following error:
```bash
WARNING in ./src/visualizations/presets/MainPreset.js 111:10-31
"export 'default' (imported as 'HelloWorldChartPlugin') was not found in '@superset-ui/plugin-chart-hello-world'
```

When going to localhost:9000, after login there is the forever loading screen and console shows the following error:

```javascript

Uncaught TypeError: _superset_ui_plugin_chart_hello_world__WEBPACK_IMPORTED_MODULE_37__.default is not a constructor
```

### After issuing the following commands...

```bash
cd $SUPERSET_REPRO_ROOT/superset-ui
yarn build
```

##  ...and restarting the dev-server...
I get the same error. Even though the dev-server command gives the following output:

```bash
[Superset Plugin] Use symlink source for @superset-ui/plugin-chart-hello-world @ ^0.0.0
```

**Expected behavior**
I should be able to go to Superset and pick the Hellow World Plugin from the list of available plugins.

**Screenshots**

**Environment (please complete the following information):**
 - superset-ui version: `v0.15.3`
 - Node version: `v12.18.3`
 - npm version: `6.14.6`
 
**Additional context**

**Comment by rusackas** [comment]
Thank you for the excellent amount of detail in your issue report! This is tremendously helpful! And there's good news, I think I see the problem!

You pointed out the error `"export 'default' (imported as 'HelloWorldChartPlugin') was not found in '@superset-ui/plugin-chart-hello-world'`

Indeed, as you mentioned, in `MainPreset` you're doing `import HelloWorldChartPlugin from '@superset-ui/plugin-chart-hello-world';`

I'm willing to bet that if you try `import { HelloWorldChartPlugin } from '@superset-ui/plugin-chart-hello-world';` it will work! The brackets mean you will be importing your plugin's "named export". You can, of course, also alter your plugin to provide a _default export_ instead, but we figured the _named export_ pattern was a little more scalable.

Hope this helps! If not, I'll keep trying to help

**Comment by codepic** [comment]
> I'm willing to bet that if you try `import { HelloWorldChartPlugin } from '@superset-ui/plugin-chart-hello-world';` it will work! The brackets mean you will be importing your plugin's "named export". You can, of course, also alter your plugin to provide a _default export_ instead, but we figured the _named export_ pattern was a little more scalable.
> 

I can verify that the change removes the error. However, I'm still not seeing the `HelloWorldChartPlugin` in the available visualizations when I go to `superset/explore` in `localhost:9000`.

The `npm run dev-server` produces me the magic `[Superset Plugin] Use symlink source for @superset-ui/plugin-chart-hello-world @ ^0.0.0` message.

When I go to `$SUPERSET_REPRO_ROOT/superset-ui` and hit `yarn jest`, I get an error message as follows:

![image](https://user-images.githubusercontent.com/3933589/93862430-577ebc80-fcc2-11ea-98fa-e9554da7fb0e.png)

But I don't think this is related to the undelying issue. Just that the `TranslatorSingleton` isn't initialized at this point.

So I go ahead and remove all the references to `t()` and its `import` under `$SUPERSET_REPRO_ROOT/superset-ui/plugins/plugin-chart-hello-world/src/` and after this, the `yarn jest` runs without errors and we're not getting any additional hints on what might be wrong.

So I turn my eye on the `yarn build` log and notice while the:

```
"babel        --config-file=../../babel.config.js src --extensions \".ts,.tsx,.js,.jsx\" --copy-files --out-dir esm"
```
compilation finishes fine and picks up the `@superset-ui/plugin-chart-hello-world` plugin, the:

```
lerna exec --stream --concurrency 3 --scope @superset-ui/{chart-controls,core,legacy-plugin-chart-country-map,legacy-plugin-chart-event-flow,legacy-plugin-chart-paired-t-test,legacy-plugin-chart-parallel-coordinates,legacy-plugin-chart-sunburst,legacy-plugin-chart-time-table,legacy-preset-chart-big-number,legacy-preset-chart-nvd3,plugin-chart-choropleth-map,plugin-chart-echarts,plugin-chart-table,plugin-chart-word-cloud,preset-chart-xy}        -- ../../scripts/tsc.sh --build
```
does not include it...

So I execute `npx lerna exec --stream --concurrency 3 --scope @superset-ui/plugin-chart-hello-world -- ../../scripts/tsc.sh --build` manually and then restart the `dev-server` but still, no plugin, no error :-/

**Comment by codepic** [comment]
I also have verified the issue really is something related to the generated plugin. I tried the following steps to replicate:

1. Do everything as previously up to the point where you would generate a plugin but don't do that.
2. Instead go to `superset-ui/plugins/plugin-chart-echarts/package.json` and rename the plugin to `@superset-ui/plugin-chart-echarts2`
3. Delete all the other plugins in the plugins directory
4. `cd $SUPERSET_REPRO_ROOT/superset-ui` and run `yarn install` and `yarn build`
5. Add `"@superset-ui/plugin-chart-echarts2": "^0.15.1",` in `superset-frontend/package.json`
6. Add `import { EchartsTimeseriesChartPlugin as EchartsTimeseriesChartPlugin2 } from '@superset-ui/plugin-chart-echarts2';` in `MainPresets.js`
7. Add `new EchartsTimeseriesChartPlugin2().configure({ key: 'echarts_timeseries2' }),` in `MainPresets.js`
8. cd `cd $SUPERSET_REPRO_ROOT/incubator-superset/superset-frontend` and run `npm link ../../superset-ui/plugins/plugin-chart-echarts2`
9. `cd $SUPERSET_REPRO_ROOT/incubator-superset/superset-frontend` and run `npm run dev-server`
10. Verify that you have now 2 ECharts Timeseries plugins. Other with key `echarts_timeseries` and other with `echarts_timeseries2`

This one works just fine and you can see the expected results. I assume this verifies that the fault is within the plugin itself and not f.ex. in the `superset-ui` or `incubator-superset` project or version compatibilty etc.

The versions for this repro were:

```bash
export SUPERSET_REPRO_ROOT=~/Desktop/superset_repro
export SUPERSET_REF=master
export SUPERSET_SHA=448a41a4e7563cafadea1e03feb5980151e8b56d
export SUPERSET_UI_VERSION=v0.15.3
```

**Comment by codepic** [comment]
Ha! Got it!

I will get back with more details but I believe the root of the problem boils down to this particular line in the `package.json` the `generator-superset` generated. It initially sets the version to `0.0.0` but I believe you need to be in same major version as the generator and/or superset-ui.

![image](https://user-images.githubusercontent.com/3933589/93892442-d25ccd00-fcec-11ea-9ca0-8c7a9f8b04bf.png)

But like I said, I will repro this and get back with more details once I've verified this indeed is the root of the problem.

Now I have to eat, debugging makes you hungry ;)

**Comment by codepic** [comment]
No, it's not the version as the process I am currently using works even if the plugin's version is `0.0.0`.

However, while the original failing procedure still fails, I have attached another process that works consistently.

[793-repro-fixed.zip](https://github.com/apache-superset/superset-ui/files/5267456/793-repro-fixed.zip)

I still do not know what actually makes the difference but it's not the package version as the attached process works even with version `0.0.0`.

**Comment by AydinChavez** [comment]
any update on this topic? am also affected.. the version from the attachment (793-repro-fixed.zip) works, but its version is a bit behind the latest release

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
