### ISSUE TITLE
Timeseries percent change chart does not show correct date in tooltip

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#795]
**Describe the bug**

> On the "timeseries percent change" superset visualization, the date in the tooltip shows up as `0Nan`

**To Reproduce**

![image](https://user-images.githubusercontent.com/1659771/93946850-341e3680-fcef-11ea-888b-3f98b3587511.png)

**Expected behavior**
`0Nan` should be replaced with date. 

**Screenshots**
![Pasted_Image_9_22_20__3_57_PM](https://user-images.githubusercontent.com/1659771/93945720-519dd100-fcec-11ea-815a-6af50718f400.png)

**Comment by junlincc** [comment]
<img width="756" alt="Screen Shot 2020-11-17 at 2 19 08 PM" src="https://user-images.githubusercontent.com/67837651/99457470-e2092400-28df-11eb-9e6b-f389257c9deb.png">
<img width="749" alt="Screen Shot 2020-11-17 at 2 17 44 PM" src="https://user-images.githubusercontent.com/67837651/99457472-e3d2e780-28df-11eb-86e6-e7fef29b3161.png">

i tried couple different datasources using timeseries percent change chart, both showing the date/time in tooltip. it seems working properly on my end. can you double check with your user?
