### ISSUE TITLE
Make page size selector optional for `DataTable`

### ISSUE THREAD

**Issue by ktmud** [apache-superset/superset-ui#796]
`DataTable` is being used by more places in Superset: https://github.com/apache/incubator-superset/pull/10982

Some of which doesn't make sense to have a page size selector.

We should make it optional by hiding the global control when users set `pageSizeOptions` to `null`.

https://github.com/apache-superset/superset-ui/blob/ffa6445956c1cfb3d71696e11a3726560aae0f5d/plugins/plugin-chart-table/src/DataTable/DataTable.tsx#L85

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
