### ISSUE TITLE
Area chart has inconsistent "stacked_style" behavior when using control panel vs. radio buttons

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#799]
#### A. via the control panel
![Pasted_Image_9_28_20__3_57_PM](https://user-images.githubusercontent.com/1659771/94494161-59a1b900-01a3-11eb-998b-9f9966484b98.png)

#### B. if "extra controls" is checked in the control panel, a set of radio buttons will appear on the chart to toggle between the 3 modes:

![Pasted_Image_9_28_20__3_57_PM](https://user-images.githubusercontent.com/1659771/94494175-62928a80-01a3-11eb-955a-bc494601eba7.png)
![Pasted_Image_9_28_20__3_58_PM](https://user-images.githubusercontent.com/1659771/94494221-7d64ff00-01a3-11eb-9007-8362f144e2f3.png)

## Problem

The `stacked_style` in the control panel and the radio buttons are not synced both ways. 
* Changing the dropdown in the control panel updates the radio buttons.
* But changing the radio buttons does not change the control panel. It only changes the area chart appearance and causes the tooltip to show incorrect values. 

### **To Reproduce**
1. Create an area chart with at least two series.
2. Go to "customize". Check the "extra controls" in the control panel
3. Change "stacked style" in the control panel to "stream". 
4. Click on the radio buttons to select "Expanded"

Notice that the dropdown in control panel and the radio buttons are showing different "stacked style". 
Also, the tooltip shows an extra column with incorrect information.

![Pasted_Image_9_28_20__4_08_PM](https://user-images.githubusercontent.com/1659771/94494834-ffa1f300-01a4-11eb-9016-328b3eac1e44.png)

5. Now change "stacked style" in the control panel to "expand". This is the **expected behavior**

![Pasted_Image_9_28_20__4_10_PM](https://user-images.githubusercontent.com/1659771/94494908-324beb80-01a5-11eb-9f51-6a64d9ff738c.png)

## **Environment (please complete the following information):**
 - superset-ui version: master

**Comment by junlincc** [comment]
@kristw yup this is still an issue and our new Echarts time series area chart is not reaching feature parity yet.
quick fix i can think about is to remove the radio button in 
`EXTRA CONTROLS`, and only use `STACKED STYLE` to change chart style. 

<img width="660" alt="Screen Shot 2020-11-17 at 5 58 13 PM" src="https://user-images.githubusercontent.com/67837651/99473769-1bea2280-2900-11eb-8abd-d7adae5e6c41.png">

**Comment by kristw** [comment]
> @kristw yup this is still an issue and our new Echarts time series area chart is not reaching feature parity yet.
> quick fix i can think about is to remove the radio button in
> `EXTRA CONTROLS`, and only use `STACKED STYLE` to change chart style.
> 
> <img alt="Screen Shot 2020-11-17 at 5 58 13 PM" width="660" src="https://user-images.githubusercontent.com/67837651/99473769-1bea2280-2900-11eb-8abd-d7adae5e6c41.png">

Should the `% of total` in the screenshot above be 10%?

**Comment by junlincc** [comment]
@kristw yea, it should be 10%.. so that's the bug. can user not use the radio button to switch style?

**Comment by kristw** [comment]
> Can user not use the radio button to switch style?

Current users are using the radio button in the dashboard. No good workaround here.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
