### ISSUE TITLE
Expandable rows in table-plugin with a subquery configuration

### ISSUE THREAD

**Issue by codepic** [apache-superset/superset-ui#805]
I am about to extend the current react-table visualization with an option to expand rows. Here's how I'd visualize it to work in the control panel.

![image](https://user-images.githubusercontent.com/3933589/95437290-7d13f300-095d-11eb-8f3e-5392a223e2fb.png)

So, when this is configured and user clicks a row on the table, the selected row's `problem_id` is passed to the plugin, then a query with the same data source is made with a where condition: `parent_problem_id==problem_id`.

### Questions
1. I'd guess I need to use `SupersetClient` to achieve the request to the data source?
2. Is there another approach to this in Superset?
3. Whichever the case, is there some existing code somewhere I could look at as a reference?

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
