### ISSUE TITLE
Email and Scheduling in superset

### ISSUE THREAD

**Issue by i4vijay** [apache-superset/superset-ui#811]
Hi All,

Need some help on the complete process of enabling email scheduling in Superset. I have enabled email feature in superset which is in a EC2 Ubuntu instance but facing difficulties in configuring celery and AWS SQS. I did searched in git hub and in stackoverflow but couldn't find the solution. Could someone share some light over here.

**Comment by mistercrunch** [comment]
close as this is duplicate with https://github.com/apache/incubator-superset/issues/11425
