### ISSUE TITLE
Echarts pie chart quirks in 0.38

### ISSUE THREAD

**Issue by bryanck** [apache-superset/superset-ui#827]
**Describe the bug**
There remain some quirks in the new Echarts-based pie chart.

1. If label lines are turned on and there is no label, e.g. the label is disabled for the slice because it doesn't meet the percent threshold, you have lines coming off the slices with no associated text.

2. The chart layout isn't automatic with the legend. If you want to fit the legend, you have to manually resize the pie chart smaller so the legend will fit. With the legend showing, the chart isn't shifted down vertically to use the unused whitespace. The chart thus needs to be smaller than before with the legend showing.

**Screenshots**

Example of 1st item:

![Screen Shot 2020-11-04 at 8 27 49 AM](https://user-images.githubusercontent.com/5475421/98139019-8fa81c00-1e78-11eb-92dc-072b15a5a1d4.png)

Example of 2nd item:

In 0.37 the chart size and layout was automatic and would fill available whitespace.
![Screen Shot 2020-11-04 at 8 46 22 AM](https://user-images.githubusercontent.com/5475421/98141005-f7f7fd00-1e7a-11eb-9524-d8b0bb547d6a.png)

In 0.38, you need to manually size the chart to fit available white space. Also, the chart layout doesn't shift down to accomodate the legend.
![Screen Shot 2020-11-04 at 8 46 16 AM](https://user-images.githubusercontent.com/5475421/98141112-1bbb4300-1e7b-11eb-8c31-2b1dc4e91193.png)

**Comment by junlincc** [comment]
@bryanck i am reposting this issue in our main repo
going forward, please file issues/enhancement request/question in https://github.com/apache/incubator-superset/issues thanks!

**Comment by junlincc** [comment]
https://github.com/apache-superset/superset-ui/pull/852  @bryanck
