### ISSUE TITLE
Adding Superset UI components to a custom React webapp

### ISSUE THREAD

**Issue by gauravsoni1** [apache-superset/superset-ui#830]
How do I add the superset UI component to a custom web application that is using React.

I need to leverage the backend of Superset but want to customise the presentation and add additional features in the web application.

**Comment by orenteriab** [comment]
@gauravsoni1 did you find anything?

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
