### ISSUE TITLE
ISO3166-2 code for China has changed in 2017

### ISSUE THREAD

**Issue by ZhangYuef** [apache-superset/superset-ui#835]
**Describe the bug**
ISO3166-2 code for China provinces has changed in 2017 while superset is still using the out-of-dated one. This problem has been raised [here](https://github.com/apache/incubator-superset/issues/10671) before.

**Expected behavior**
We should modify the 'ISO' in china.geojson file (b3c8bf97ee7cc642bf10e0eecbe25c36.geojson)

**Screenshots**
The ISO3166-2 version we have in superset now is as following:
![image](https://user-images.githubusercontent.com/20250982/99143688-560fa780-2614-11eb-8ddd-c179873ab38a.png)

**Environment (please complete the following information):**
 - superset-ui version: [0.37.2]
 - python version: [3.7]

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
