### ISSUE TITLE
Adding annotation formula to bar chart add more bars instead of line

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#838]
**Describe the bug**

**To Reproduce**
1. Go to explore
2. Create time-series bar chart
3. Add annotation layer
4. Set y=constant e.g. `y=100` as formula

![image](https://user-images.githubusercontent.com/1659771/99842765-4963e580-2b25-11eb-9516-bc63672ab803.png)

**Expected behavior**
A horizontal line at y 100

**Screenshots**
It adds a bar for each grouped bar instead.

<img width="922" alt="Pasted_Image_11_20_20__11_37_AM" src="https://user-images.githubusercontent.com/1659771/99842565-ec682f80-2b24-11eb-8749-b669e88b401c.png">

**Environment (please complete the following information):**
 - superset-ui version: current

**Comment by junlincc** [comment]
@kristw im moving this issue to the main repo. can you post all the future issues there? 🙏

**Comment by kristw** [comment]
https://github.com/apache/incubator-superset/issues/11909
