### ISSUE TITLE
String columns can be incorrectly date-formatted

### ISSUE THREAD

**Issue by altef** [apache-superset/superset-ui#857]
**Describe the bug**

String columns can be incorrectly date-formatted, if _any_ rows in the result set begin with a date.

I believe I've tracked this back to: https://github.com/apache-superset/superset-ui/blob/f45cfaf949e8c6e03e33fc66f4794d4d9a433b1b/plugins/plugin-chart-table/src/transformProps.ts#L59

It tests the [regex `/^\d{4}-[01]\d-[03]\d/`](https://github.com/apache-superset/superset-ui/blob/master/plugins/plugin-chart-table/src/transformProps.ts#L53) (which, by the way, does this match days in the teens and twenties?).  Since the regex only checks to see if the beginning of the string matches, it can inaccurately classify values that are not dates as dates, which results in the `0NaN-NaN-NaN NaN:NaN:NaN` strings, below.

It appears that [as long as any one element passes this check](https://github.com/apache-superset/superset-ui/blob/master/plugins/plugin-chart-table/src/transformProps.ts#L57), the column will be classified as a date.

**To Reproduce**
1. Create a varchar/string entry in your data set with the value `2020-08-31_this is not a date.gif`.
2. Create a chart with the table visualization type that queries that dataset.
3. Click run.
4. (See error)

**Expected behavior**

Ideally those strings would appear as they are in the table.

**Screenshots**

![image](https://user-images.githubusercontent.com/4316295/101675397-98a78280-3a0e-11eb-8d77-108ab99ab028.png)

**Environment (please complete the following information):**

 - superset-ui version: `0.15.13`
 - Node version: `v13.11.0`
 - npm version: `6.13.7`
 
**Additional context**

Similar to issue  #731

**Comment by ktmud** [comment]
Thanks for reporting this issue! I'll take a look soon.

**Comment by altef** [comment]
@ktmud Were you able to reproduce it?  I've fixed this locally on my end by changing  [`data.some` to `data.every` ](https://github.com/apache-superset/superset-ui/blob/f45cfaf949e8c6e03e33fc66f4794d4d9a433b1b/plugins/plugin-chart-table/src/transformProps.ts#L57) but that may have some ramifications (with null dates, or malformed strings) that don't matter for my uses but likely may to the wider community.

**Comment by ktmud** [comment]
@altef Could you test this in the latest Superset `master` branch? The table chart no longer uses regular expression to identify time columns but rather have moved that column type inference logic to the backend.

**Comment by altef** [comment]
Will do! (and will reply here - Thanks!)

**Comment by altef** [comment]
Looks like it worked for me! This was my test sequence:

1. `git pull`
2. `npm ci`
3. `npm run prod`
4. restart the service
5. load previously erroring chart, and see string names rather than NaN date strings

Thanks! :D

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
