### ISSUE TITLE
plugin-chart-table not using new API?

### ISSUE THREAD

**Issue by AydinChavez** [apache-superset/superset-ui#859]
The README.MD states:

_@superset-ui/plugin-* packages are newer and higher quality in general. A key difference that they do not depend on viz.py (which contain visualization-specific python code) and interface with /api/v1/query/, a new generic endpoint instead meant to serve all visualizations, instead._ 

But according to
https://github.com/apache-superset/superset-ui/blob/master/plugins/plugin-chart-table/src/index.ts#L31
it's still using the legacy api (viz.py) ?

I would expect that it uses the new api as stated in the doc.

**Comment by ktmud** [comment]
We are in the process of migrating it to the new API. The table chart was completely rewritten recently but the API was kept the same as the first iteration.

**Comment by AydinChavez** [comment]
Do you know when the migration towards the new API for this particular table chart plugin will be finished?

**Comment by ktmud** [comment]
Before EOY.

**Comment by AydinChavez** [comment]
Okay, great.

**Comment by AydinChavez** [comment]
Any update on this one?

**Comment by maxenz** [comment]
I'm having the same problem, any news? I always get no records found...

**Comment by ktmud** [comment]
Hi, the table chart has been migrated to the new API: https://github.com/apache-superset/superset-ui/pull/889

We are still actively working on this chart, so feel free to report any bugs you saw or other feature requests for the table chart in the main Superset repo: https://github.com/apache/superset/issues
