### ISSUE TITLE
Pivot table not showing values for aggregated string values

### ISSUE THREAD

**Issue by villebro** [apache-superset/superset-ui#868]
### Describe the bug

Pivot table incorrectly removes valid string cell values when conditionally applying formatting/removing null values.

### To Reproduce

1. Go to Explore View and choose `birth_names` as the dataset.
2. Choose Pivot Table viz type.
3. Choose 'gender` as the groupby
4. Choose 'MAX(gender)` as the metric.

### Expected behavior

Strings should appear in the cells.

### Screenshots

![image](https://user-images.githubusercontent.com/33317356/102343974-e50d3800-3fa3-11eb-8928-3656e1f0321f.png)

### Additional context

Since the reformatting logic is fairly complex, it would make sense to break out the main formatting logic into a separate function(s) and add relevant unit tests to guard against future regressions.

**Comment by junlincc** [comment]
resolved in master but the fix seems did not get into the patch release? Ville can you help confirm? @villebro 🙏
