### ISSUE TITLE
custom sql convert to query is undefined

### ISSUE THREAD

**Issue by zxcvbnmzsedr** [apache-superset/superset-ui#876]
### Describe the bug

![image](https://user-images.githubusercontent.com/14026790/102775969-e4700980-43c8-11eb-8f8f-57265256a427.png)

### To Reproduce
if ‘appendWhere’ is undefined and 'where' is not undefined

It will splice one on top of the final SQL ‘undefined’

like ((date_format(时间, '%Y-%m') = date_format(curdate(), '%Y-%m'))) AND undefined

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
