### ISSUE TITLE
Line Chart Time Series markers not correct after zoom

### ISSUE THREAD

**Issue by PRijnbeek** [apache-superset/superset-ui#881]
### Describe the bug

When you use the zoom bar at the bottom and then use the mouse to hoover over the chart, the markers are not lined up correctly with the line.

### To Reproduce

1. Go to Top 10 California Names Timeseries
2. Zoom in with the zoom bar at the bottom
3. Click on the chart to show the vertical line
4. The markers are too much to the left (it is not taking into consideration it is zoomed)

### Expected behavior

Markers are on the line as is the case without zoom

### Screenshots

No zoom:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/7252105/103033185-2b453700-4562-11eb-96c6-35b77052a1af.png">

With zoom:

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/7252105/103033248-5596f480-4562-11eb-92ad-198f00c868e9.png">

### Environment (please complete the following information):

- superset-ui version: v0.999.0dev
- Node version: v12.20.0
- npm version: 6.14.8

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
