### ISSUE TITLE
Integrate Superset dashboards into an Angular application

### ISSUE THREAD

**Issue by ILoveITScience** [apache-superset/superset-ui#888]
I want to integrate Superset dashboards into an Angular application. Unfortunately I don't have a working instance of Superset yet but I have some questinos:

1) Is it possible to integrate dashboards via IFrames?
2) Are there any other ways to integrate dashboards into other web applications.
3) I found the superset-ui project. It seems to provide the same components that are used in Superset (at least the legacy once). But these are just the pure JavaScript components, right?. I'm wondering how to fetch the data to the components? Does Superset provide an API to fetch the data or do I have to write a backend services on my own.

**Comment by orenteriab** [comment]
Hey @ILoveITScience - Do you have any findings?

We'd like to integrate superset into our application, but the results I've gotten are very quirky, I have a lot of problems rendering the components (it seems the styling of superset-ui and superset is pretty tied). Also, I have some components that doesn't render at all, but they doesn't fail either.

And the docs aren't super helpful.

**Comment by gokultrivandrum** [comment]
@ILoveITScience  Are you able to find any solution ?


CC : @orenteriab

**Comment by nileio** [comment]
can you post a sample solution?

**Comment by BFergerson** [comment]
This is not my work, but it seems @aksth has been a bit busy with https://github.com/aksth/superset-embedding.

If you end up using this work, please keep this issue updated. I'm not a strong web developer so I'm not 100% sure how to make use of this work, but it's obvious we're headed in the right direction. @aksth mentions a full working angular application should be coming soon. Maybe someone here could help.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
