### ISSUE TITLE
Make the message for no results a parameter

### ISSUE THREAD

**Issue by PRijnbeek** [apache-superset/superset-ui#893]
### Is your feature request related to a problem? Please describe.

Currently the text that is displayed when there are no results is hardcoded [here](https://github.com/apache-superset/superset-ui/blob/543e6b15e013a67be2a3c9bdb8244ea19dbb4877/packages/superset-ui-core/src/chart/components/NoResultsComponent.tsx#L8)

### Describe the solution you'd like

Add this as a variable in the backend

### Additional context

We have dashboards that contain charts that may not contain data and this is expected for certain situations, you then do not want the current message.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
