### ISSUE TITLE
Please help! How does getChartComponentRegistry work in SuperChartCore?

### ISSUE THREAD

**Issue by sysstudy20** [apache-superset/superset-ui#902]
I recently started looking into the `Superset` codebase and having a hard time grasping how some parts work.
In the `SuperChart` component, which I assume works as a parent component for all chart types that `Superset` has, it uses a `SuperChartCore` component, which has the core logic of it.

https://github.com/apache-superset/superset-ui/blob/4bda6f5305ea51225bd3eaed93d19a2f93a3f04c/packages/superset-ui-core/src/chart/components/SuperChartCore.tsx#L102

In this part of the code, 

```
const Renderer = createLoadableRenderer({
          loader: {
            Chart: () => getChartComponentRegistry().getAsPromise(chartType),
            transformProps: overrideTransformProps
              ? () => Promise.resolve(overrideTransformProps)
              : () => getChartTransformPropsRegistry().getAsPromise(chartType),
          },
```

I think `createLoadableRenderer` takes care of rendering the chart based on the `chartType` string passed in. However, I am still not sure how `getChartComponentRegistry()` works.

I looked into the file https://github.com/apache-superset/superset-ui/blob/4bda6f5305ea51225bd3eaed93d19a2f93a3f04c/packages/superset-ui-core/src/chart/registries/ChartComponentRegistrySingleton.ts to understand further.

What I am missing is, if I try to debug what `getChartComponentRegistry()` tries to return, I see something like

```
{
 items: {area: {loader: f}, bar: {loader: f} ...},
 name: 'ChartComponent',
 overwritePolicy: 'ALLOW',
 promises: {}
}
```

but I am not sure where the `items` come from. I don't see anywhere in the code that puts in the `loaders` into the `items` object. 

Please help me understanding the logic. Thanks!

**Comment by ktmud** [comment]
They are registered in [`superset/supersetfrontend`](https://github.com/apache/superset/blob/fecfc34cd3e3dd2efb8daee03d6416384914cc8a/superset-frontend/src/visualizations/presets/MainPreset.js), which in terms calls the [Preset.ts](https://github.com/apache-superset/superset-ui/blob/dc804b7a707e0cb8c29fc129bfff2c9aa143fd62/packages/superset-ui-core/src/models/Preset.ts) that calls each plugin's [`register()`](https://github.com/apache-superset/superset-ui/blob/0c22b8e5edb017818f8b0cfb298c397f2ead983e/packages/superset-ui-core/src/chart/models/ChartPlugin.ts#L104) function that puts each part of the plugin into different registries... 

Man, this is so convoluted.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
