### ISSUE TITLE
Show/Hide respective tabs according to the filters onchange

### ISSUE THREAD

**Issue by monikabala** [apache-superset/superset-ui#907]
Hi,
I am using superset in linux. Can anyone suggest how to show/hide the tabs with respect to filters onchange?
Here i have country, state and city. So when i select any  state from dropdown it should display the employed and unemployed tabs alone.
![superset_issue](https://user-images.githubusercontent.com/55377096/105452066-a2760400-5ca3-11eb-9723-91933d9a789e.png)

Also please let me know the path where i can write code for it.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
