### ISSUE TITLE
Safeguard JSON.stringify

### ISSUE THREAD

**Issue by kristw** [apache-superset/superset-ui#91]
**Is your feature request related to a problem? Please describe.**
`JSON.stringify` crashes when given circular structure.

**Describe alternatives you've considered**
1) Use non-native alternative such as 
https://www.npmjs.com/package/fast-safe-stringify
2) Consider developer needs to pass non-circular structure.

**Additional context**
Currently `JSON.stringify` is only used in `SupersetClient`

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
