### ISSUE TITLE
error when run yarn build

### ISSUE THREAD

**Issue by toop** [apache-superset/superset-ui#926]
node ：v12.16.4
yarn: v1.22.4
npm: v6.14.4
os: win10

error info：
D:\superset-ui-0.16.9>yarn babel
yarn run v1.22.4
$ yarn build --no-type
$ node ./scripts/build.js --no-type
--- Run babel --------

>> lerna exec --stream --concurrency 10 --scope @superset-ui/!(demo|generator-superset)
         -- babel --config-file=../../babel.config.js src --extensions ".ts,.tsx,.js,.jsx" --copy-files --out-dir lib

Done in 0.58s.

=========================
D:\superset-ui-0.17.6>yarn install
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...

**Comment by toop** [comment]
It·s worked on the ubuntu

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
