### ISSUE TITLE
Time Series Table counts null as 0

### ISSUE THREAD

**Issue by pavlozt** [apache-superset/superset-ui#941]
### 
When using use Time-series Table , the grouping functions count the missing values as 0, but to be counted as NULL.

### To Reproduce

   1. Choose Chart Type : Time-series Table
   2. group by Field
   3. Time series columns
   4. Type : Period Average
   5. time lag - any value choose any value that would grab the missing data

### Expected behavior

Traditional sql-like behavior that avg() function not count nulls.

- superset-ui version: 1.0

### Additional context
see bug and conversation in superset github
https://github.com/apache/superset/issues/12962

arithmetically wrong code need be rewrited 

superset-ui\plugins\legacy-plugin-chart-time-table\src\TimeTable.tsx

} else if (column.colType === 'avg') {
  // Average over the last {timeLag}
  v =
    reversedEntries
      .map((k: Entry, i: number) => (i < column.timeLag ? k[valueField] : 0))
      .reduce((a: number, b: number) => a + b) / column.timeLag;
}

**Comment by junlincc** [comment]
@pavlozt thanks for reporting, i was able to reproduce, let's keep the conversation in the main repo

https://github.com/apache/superset/issues/12962#issuecomment-774851944
