### ISSUE TITLE
How to use a new type of plug-in to customize charts?

### ISSUE THREAD

**Issue by Tyroo** [apache-superset/superset-ui#966]
The old type plug-in dependency viz.py returns data, but the new type plug-in no longer depends on it (adding a new class to it is invalid). Can you provide us with some solutions so that we can achieve our previous goal?

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
