### ISSUE TITLE
ChartClient doesn't match /api/v1/chart/data endpoint schema

### ISSUE THREAD

**Issue by cjwooo** [apache-superset/superset-ui#975]
### Describe the bug

I'm using the superset-ui components to add some charts to my webapp, using the ChartDataProvider from superset-ui/core. It works as expected with the legacy chart plugins, but when I try to create a Timeseries chart, which uses the new API, the ChartDataProvider (specifically, its underlying ChartClient), generates a request body to /api/v1/chart/data of the form `{query_context: {datasource: ...}}` , whereas my local Superset instance expects a request body `{datasource: ...}` without the "query_context" wrapper key. Similarly, it does not handle the response properly as well, expecting a response of `{result: {data: ...}}` as opposed to the actual result of `{data: ...}`.  Am I doing something wrong here? I'm using superset-ui packages of version ^0.17.10 against Superset backend version 1.0.1.

### To Reproduce

Deploy a local Superset instance. Create a react webapp with a page that uses the ChartDataProvider to create a Timeseries chart, or other chart type that uses the new /chart/data endpoint. Open your web browser's developer console and inspect the network request to `http://localhost:8088/api/v1/chart/data`. The response will be code 400 with body:
```
{
  "message": "Request is incorrect: {'query_context': ['Unknown field.']}"
}
```

### Environment (please complete the following information):

- superset-ui version: 0.17.10
- superset version: 1.0.1
- Node version: 14.15.5
- npm version: 6.14.11
- yarn version: 1.22.10

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://github.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: https://github.com/apache/superset/issues/13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
